/**
 * Ergo (ERG) ChainAdapter.
 *
 * Industry-standard Ergo wallet — matches Nautilus / SAFEW / Yoroi
 * derivation byte-for-byte. A mnemonic generated by Pwnda will produce
 * the same address if imported into any of those wallets, and vice-versa.
 *
 * ## Cryptography
 *
 *   BIP-39 mnemonic  (12/15/18/21/24 words; Pwnda generates 12 by default)
 *     │
 *     ▼  PBKDF2-HMAC-SHA512(salt = "mnemonic" + passphrase, 2048 rounds)
 *   64-byte BIP-32 master seed   ← via @scure/bip39, same lib as every other Pwnda chain
 *     │
 *     ▼  BIP-32 child derivation via @scure/bip32 (spec-compliant 32-byte ser256)
 *   Child key at m/44'/429'/0'/0/0   ← EIP-3 standard path; coin type 429 = ascii("ergo")
 *     │
 *     ▼  ErgoAddress.fromPublicKey(child.publicKey)
 *   P2PK Base58 address, mainnet prefix "9"
 *
 * Why @scure/bip32 instead of Fleet's `ExtendedSecretKey.fromMasterSeed`:
 *   - Same primitive Pwnda already uses for every other BIP-32 chain
 *     (btc, ltc, doge, bch, rvn, eth, etc.) — audited, well-tested.
 *   - Both are spec-compliant (ser256 zero-padded to 32 bytes) so output
 *     is byte-identical to Fleet. This is the SAFE side of the Ergo
 *     ecosystem derivation split documented at [[Ergo]] §"Critical: the
 *     ecosystem derivation split". The Ergo node wallet (and old mobile
 *     wallets) are on the buggy side using BigIntegers.asUnsignedByteArray;
 *     Pwnda is on the Nautilus side.
 *   - Minimizes Fleet's blast radius. If a future Fleet bump regresses,
 *     only address encoding / tx building / signing is affected — not
 *     derivation. The derivation lock test in `derivation-paths.test.ts`
 *     catches any drift in either direction.
 *
 * ## Sending
 *
 * Ergo is **eUTXO**. A naive ERG send via Fleet's auto-`build()` BURNS
 * tokens on the input boxes if any are present (Fleet only sweeps ERG
 * back to the change address; tokens vanish into the miner-fee box).
 * `sendTransaction` below explicitly pre-selects inputs, aggregates all
 * tokens across selected inputs, and emits them on the change output
 * via `OutputBuilder.addTokens()`. Mainnet validated via testnet
 * gauntlet per [[ergo-integration-plan]] Procedure #2.
 *
 * ## Explorer API
 *
 * REST via `erg-rpc.ts` failover wrapper: api.ergoplatform.com primary,
 * api.sigmaspace.io drop-in mirror. Schemas are identical.
 *
 * ## Out of scope (v1)
 *
 *   - Token (native asset) display on the balance screen — tokens are
 *     preserved on send but not shown in the balance/history views,
 *     matching how Pwnda's other adapters treat secondary assets
 *     (BTC adapter doesn't list ordinals; ETH adapter doesn't list
 *     every ERC-20 in the receive UI).
 *   - NFT awareness — same reason.
 *   - dApp connector (EIP-12) — Pwnda isn't a browser extension.
 *   - "Send Max" affordance for the dust-change edge case — error UI
 *     rejects the send with a clear message; v2 candidate.
 *
 * See [[Ergo]], [[autolykos-v2]], [[ergo-integration-plan]].
 */

import { mnemonicToSeedSync } from "@scure/bip39";
import { HDKey } from "@scure/bip32";
import { getPublicKey } from "@noble/secp256k1";
import {
  ErgoAddress,
  OutputBuilder,
  RECOMMENDED_MIN_FEE_VALUE,
  SAFE_MIN_BOX_VALUE,
  TransactionBuilder,
} from "@fleet-sdk/core";
import { ErgoHDKey, Prover } from "@fleet-sdk/wallet";
import type {
  ChainAdapter,
  WalletInfo,
  TxResult,
  NetworkInfo,
  ChainTx,
  TxHistoryPage,
  FeeEstimate,
} from "./types";
import { ergoGet, ergoSubmitTx, ErgoRpcError } from "./erg-rpc";

const DERIVATION_PATH = "m/44'/429'/0'/0/0";

const NANO_PER_ERG = 1_000_000_000n;

// =========================================================================
// Derivation
// =========================================================================

function trimMnemonic(m: string): string {
  return m.trim().split(/\s+/).join(" ");
}

function bytesToHex(b: Uint8Array): string {
  return Array.from(b)
    .map((x) => x.toString(16).padStart(2, "0"))
    .join("");
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  if (clean.length !== 64) {
    throw new Error(
      `Invalid Ergo private key length: expected 32-byte hex (64 chars), got ${clean.length}`,
    );
  }
  const out = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    out[i] = parseInt(clean.substr(i * 2, 2), 16);
  }
  return out;
}

function deriveFromMnemonicInternal(mnemonic: string, path: string = DERIVATION_PATH): WalletInfo {
  const clean = trimMnemonic(mnemonic);
  if (!clean) throw new Error("Empty mnemonic");
  const seed = mnemonicToSeedSync(clean, "");
  const root = HDKey.fromMasterSeed(seed);
  const child = root.derive(path);
  if (!child.privateKey || !child.publicKey) {
    throw new Error("BIP-32 derivation produced no key material");
  }
  const address = ErgoAddress.fromPublicKey(child.publicKey).encode();
  return {
    chain: "ergo",
    address,
    mnemonic: clean,
    privateKey: bytesToHex(child.privateKey),
  };
}

function addressFromPrivateKey(privHex: string): string {
  const priv = hexToBytes(privHex);
  // Ergo's Sigma curve uses the same secp256k1 as BTC/ETH; the public-key
  // encoding is the only Ergo-specific bit. We don't have an xpriv here,
  // so compute the compressed (33-byte) pub directly via @noble/secp256k1.
  const pub = getPublicKey(priv, true);
  return ErgoAddress.fromPublicKey(pub).encode();
}

// =========================================================================
// Address validation
// =========================================================================

function validateAddress(addr: string): void {
  try {
    ErgoAddress.fromBase58(addr);
  } catch (e: any) {
    throw new Error(`Invalid Ergo address: ${addr} (${e?.message ?? e})`);
  }
}

// =========================================================================
// Balance + history + network info
// =========================================================================

interface ExplorerBalanceResp {
  /** confirmed/unconfirmed total in nanoERG, as a string */
  nanoErgs: string;
  /** native tokens held; we surface only ERG in v1 balance display */
  tokens?: Array<{ tokenId: string; amount: string }>;
}

interface ExplorerTxResp {
  items: ExplorerTxRow[];
  total: number;
}

interface ExplorerTxRow {
  id: string;
  timestamp: number; // unix-ms per Ergo explorer convention
  /** Block height the tx was included in; 0 / absent for mempool */
  inclusionHeight?: number;
  /** Total inputs from this address (nanoERG, string) */
  inputs: Array<{
    address?: string;
    value: string;
  }>;
  outputs: Array<{
    address?: string;
    value: string;
  }>;
  /** Confirmation count from the explorer ("numConfirmations" varies by
   *  API version — also seen as `confirmationsCount`). */
  numConfirmations?: number;
  confirmationsCount?: number;
}

function nanoErgToErg(nano: bigint): string {
  // Render with up to 9 decimal places, trimmed of trailing zeros.
  const whole = nano / NANO_PER_ERG;
  const frac = nano % NANO_PER_ERG;
  if (frac === 0n) return whole.toString();
  let fracStr = frac.toString().padStart(9, "0");
  fracStr = fracStr.replace(/0+$/, "");
  return `${whole}.${fracStr}`;
}

function ergToNanoErg(amountErg: string): bigint {
  const trimmed = amountErg.trim();
  if (!/^\d+(\.\d+)?$/.test(trimmed)) {
    throw new Error(`Invalid ERG amount: ${amountErg}`);
  }
  const [whole, frac = ""] = trimmed.split(".");
  if (frac.length > 9) {
    throw new Error(`ERG amount has more than 9 decimal places: ${amountErg}`);
  }
  const padded = frac.padEnd(9, "0");
  return BigInt(whole) * NANO_PER_ERG + BigInt(padded || "0");
}

async function getBalance(address: string): Promise<string> {
  const j = await ergoGet<ExplorerBalanceResp>(
    `/addresses/${address}/balance/confirmed`,
  );
  return nanoErgToErg(BigInt(j.nanoErgs || "0"));
}

function classifyTxDirection(
  ownAddr: string,
  row: ExplorerTxRow,
): {
  direction: "in" | "out" | "self";
  amount: bigint;
  counterparty?: string;
} {
  // For an eUTXO row from the explorer, sum nano-value contributed by
  // `ownAddr` on each side. Direction = sign of (outs - ins).
  let ownIn = 0n;
  let ownOut = 0n;
  let counterIn: string | undefined;
  let counterOut: string | undefined;
  for (const i of row.inputs ?? []) {
    if (i.address === ownAddr) ownIn += BigInt(i.value || "0");
    else if (i.address && !counterIn) counterIn = i.address;
  }
  for (const o of row.outputs ?? []) {
    if (o.address === ownAddr) ownOut += BigInt(o.value || "0");
    else if (o.address && !counterOut) counterOut = o.address;
  }
  const delta = ownOut - ownIn;
  if (delta === 0n && ownIn > 0n) {
    return { direction: "self", amount: ownIn, counterparty: counterIn };
  }
  if (delta > 0n) {
    return { direction: "in", amount: delta, counterparty: counterIn };
  }
  return { direction: "out", amount: -delta, counterparty: counterOut };
}

async function getTransactionHistory(
  address: string,
  opts?: { limit?: number; cursor?: string },
): Promise<TxHistoryPage> {
  const limit = Math.min(opts?.limit ?? 25, 50);
  const offset = opts?.cursor ? Math.max(0, parseInt(opts.cursor, 10)) : 0;
  const j = await ergoGet<ExplorerTxResp>(
    `/addresses/${address}/transactions?offset=${offset}&limit=${limit}`,
  );
  const items: ChainTx[] = (j.items ?? []).map((row) => {
    const { direction, amount, counterparty } = classifyTxDirection(
      address,
      row,
    );
    const confirmations =
      row.numConfirmations ?? row.confirmationsCount ?? undefined;
    return {
      chain: "ergo",
      hash: row.id,
      direction,
      amount: nanoErgToErg(amount),
      timestamp: row.timestamp ? Math.floor(row.timestamp / 1000) : undefined,
      confirmations,
      height: row.inclusionHeight,
      counterparty,
    } satisfies ChainTx;
  });
  const nextOffset = offset + items.length;
  return {
    items,
    cursor: items.length === limit ? String(nextOffset) : undefined,
  };
}

async function getNetworkInfo(): Promise<NetworkInfo> {
  const j = await ergoGet<{ height?: number }>(`/info`);
  return {
    label: "Block height",
    value: String(j.height ?? 0),
    unit: "blocks",
  };
}

/**
 * Ergo's miner-fee market is unusually flat. The network minimum is
 * 1,000,000 nanoERG (0.001 ERG) and almost every miner accepts that —
 * there's no real "fast vs slow" gradient because blocks are 2 minutes
 * and the dataset only forms once. Fleet's `RECOMMENDED_MIN_FEE_VALUE`
 * pads to 1,100,000 (0.0011 ERG) for safety headroom. We surface the
 * recommended value and don't bother with multi-tier UX.
 */
async function getFeeEstimate(): Promise<FeeEstimate> {
  const nano = RECOMMENDED_MIN_FEE_VALUE; // bigint
  const value = nanoErgToErg(nano);
  return {
    normal: { value, eta: "≈ 2 min" },
    unit: "ERG",
    fetchedAt: Date.now(),
    raw: { nanoErg: nano.toString() },
  };
}

// =========================================================================
// Send
// =========================================================================

interface UnspentBox {
  boxId: string;
  value: string; // nanoERG
  ergoTree: string;
  assets?: Array<{ tokenId: string; amount: string }>;
  additionalRegisters?: Record<string, string>;
  creationHeight: number;
  transactionId: string;
  index: number;
}

function greedySelectBoxes(boxes: UnspentBox[], needed: bigint): UnspentBox[] {
  // Sort by value desc → minimize input count.
  const sorted = [...boxes].sort((a, b) => {
    const av = BigInt(a.value);
    const bv = BigInt(b.value);
    return av < bv ? 1 : av > bv ? -1 : 0;
  });
  const out: UnspentBox[] = [];
  let total = 0n;
  for (const b of sorted) {
    out.push(b);
    total += BigInt(b.value);
    if (total >= needed) return out;
  }
  throw new Error(
    `Insufficient balance: have ${nanoErgToErg(total)} ERG, need ${nanoErgToErg(needed)} ERG`,
  );
}

function aggregateTokens(
  boxes: UnspentBox[],
): Array<{ tokenId: string; amount: string }> {
  const sums = new Map<string, bigint>();
  for (const b of boxes) {
    for (const a of b.assets ?? []) {
      const cur = sums.get(a.tokenId) ?? 0n;
      sums.set(a.tokenId, cur + BigInt(a.amount));
    }
  }
  return Array.from(sums.entries()).map(([tokenId, amount]) => ({
    tokenId,
    amount: amount.toString(),
  }));
}

async function sendTransaction(
  privateKeyHex: string,
  to: string,
  amount: string,
): Promise<TxResult> {
  validateAddress(to);
  const fromAddress = addressFromPrivateKey(privateKeyHex);
  const amountNano = ergToNanoErg(amount);
  if (amountNano < SAFE_MIN_BOX_VALUE) {
    throw new Error(
      `Amount below Ergo dust threshold (need ≥ ${nanoErgToErg(SAFE_MIN_BOX_VALUE)} ERG)`,
    );
  }

  // 1. Fetch unspent boxes + current height in parallel.
  const [boxesResp, info] = await Promise.all([
    ergoGet<{ items: UnspentBox[] }>(
      `/boxes/unspent/byAddress/${fromAddress}?offset=0&limit=200`,
    ).catch((e: unknown) => {
      // Explorer v1 sometimes returns 404 instead of empty when the address
      // has never been funded. Treat as zero boxes.
      if (e instanceof ErgoRpcError) {
        const all404 = e.attempts.every((a) => a.status === 404);
        if (all404) return { items: [] };
      }
      throw e;
    }),
    ergoGet<{ height: number }>(`/info`),
  ]);

  const boxes = boxesResp.items ?? [];
  if (boxes.length === 0) {
    throw new Error("No unspent boxes for sender address");
  }

  // 2. Greedy box selection covering amount + fee + dust-headroom for change.
  const fee = RECOMMENDED_MIN_FEE_VALUE; // bigint
  const needed = amountNano + fee + SAFE_MIN_BOX_VALUE;
  const selected = greedySelectBoxes(boxes, needed);

  // 3. Compute change. If change would be dust, refuse (PR-6c will add Send Max).
  const inSum = selected.reduce((s, b) => s + BigInt(b.value), 0n);
  const change = inSum - amountNano - fee;
  if (change < SAFE_MIN_BOX_VALUE) {
    throw new Error(
      "Amount too close to balance — change would be dust. Reduce amount " +
        `(or use Send Max in a future release). need ≥ ${nanoErgToErg(SAFE_MIN_BOX_VALUE)} ERG headroom.`,
    );
  }

  // 4. Aggregate all tokens across selected inputs onto the change output.
  //    Without this Fleet's auto-build burns them. This is the eUTXO
  //    footgun documented at [[ergo-integration-plan]] §Procedure #2.
  const tokenSums = aggregateTokens(selected);
  const changeOutput = new OutputBuilder(change, fromAddress);
  if (tokenSums.length > 0) {
    changeOutput.addTokens(tokenSums);
  }

  // 5. Build the unsigned tx. Fleet's `Box<Amount>` accepts string-typed
  //    `value` / `amount` (the `Amount` type union includes `string`), so
  //    the raw explorer response shape works without per-field BigInt
  //    conversion. The chain `.from(...).to(...).payFee(...).build()`
  //    produces an `ErgoUnsignedTransaction`; `.toEIP12Object()`
  //    serializes it into the form `Prover.signTransaction` consumes.
  const unsignedTx = new TransactionBuilder(info.height)
    .from(selected as unknown as Parameters<TransactionBuilder["from"]>[0])
    .to([new OutputBuilder(amountNano, to), changeOutput])
    .payFee(fee)
    .build()
    .toEIP12Object();

  // 6. Sign via Fleet's Prover.
  //    Pwnda's adapter contract hands us a 32-byte private key in hex.
  //    Fleet's `ErgoHDKey` constructor accepts `{ privateKey, chainCode }`.
  //    Since this is a single-key sign (no further BIP-32 child derivation
  //    needed inside the prover), an all-zero chain code is fine — the
  //    chain code only matters when you ask the key to `.derive(...)`.
  //    The derivation lock test in `derivation-paths.test.ts` is the
  //    canary if Fleet ever changes this contract.
  const priv = hexToBytes(privateKeyHex);
  const hdKey = new ErgoHDKey({
    privateKey: priv,
    chainCode: new Uint8Array(32),
  });
  const signedTx = new Prover().signTransaction(unsignedTx, [hdKey]);

  // 7. Submit via mirror failover.
  try {
    const result = await ergoSubmitTx(signedTx);
    return { hash: result.id };
  } catch (e) {
    if (e instanceof ErgoRpcError) {
      const trail = e.attempts
        .map((a) => `${a.base} (${a.status})`)
        .join(", ");
      throw new Error(`Ergo broadcast failed across all mirrors: ${trail}`);
    }
    throw e;
  }
}

// =========================================================================
// Import paths
// =========================================================================

function importFromMnemonic(mnemonic: string): WalletInfo {
  return deriveFromMnemonicInternal(mnemonic);
}

function importFromPrivateKey(privateKey: string): WalletInfo {
  const clean = privateKey.trim();
  const address = addressFromPrivateKey(clean);
  return {
    chain: "ergo",
    address,
    mnemonic: "",
    privateKey: clean.startsWith("0x") ? clean.slice(2) : clean,
  };
}

// =========================================================================
// Adapter export
// =========================================================================

export const ergoAdapter: ChainAdapter = {
  chain: "ergo",
  displayName: "Ergo",
  ticker: "ERG",
  color: "#FF5829",
  addressPlaceholder: "9...",
  derivation: {
    kind: "bip39",
    path: "m/44'/429'/0'/0/0",
    standard: "EIP-3 — Nautilus, Yoroi-Ergo",
    hasAlternatives: false,
  },
  /** Arbitrary-path derivation — powers the generic finder + funded-path scan. */
  deriveAtPath(mnemonic: string, path: string): WalletInfo {
    return deriveFromMnemonicInternal(mnemonic, path);
  },

  importFromMnemonic,
  importFromPrivateKey,
  deriveFromMnemonic: deriveFromMnemonicInternal,
  getBalance,
  sendTransaction,
  getNetworkInfo,
  getTransactionHistory,
  getFeeEstimate,
};
