/**
 * Settings ▸ Wallets ▸ Add / Import takes one box for every seed kind. Until
 * 2026-09-13 a Zano seed there read "Unrecognized", so a second Zano wallet
 * could not be added at all. These pin that each kind is recognised, and that
 * the kinds cannot be mistaken for one another.
 *
 * Fixed vectors only. The first version generated seeds, and every seed
 * generator takes entropy from the Tauri-backed secure RNG, which does not
 * exist under Node (`ReferenceError: window is not defined`).
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { detectSeedKind } from "./seed-kind";
import { verifyXelisSeedIntegrity } from "./xelis-keys";
import { validateXmrSeed } from "./xmr-keys";

// The Xelis check belongs to the contract module, which throws until
// WALLET-CORE implements it. Wrapped so a test can say what it answers; the
// default stays the REAL function, so these tests mean the same thing before
// and after WALLET-CORE lands.
vi.mock("./xelis-keys", async (importOriginal) => {
  const real = await importOriginal<typeof import("./xelis-keys")>();
  return { ...real, verifyXelisSeedIntegrity: vi.fn(real.verifyXelisSeedIntegrity) };
});
const xelisCheck = vi.mocked(verifyXelisSeedIntegrity);

const BIP39 =
  "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";

// The Zano vectors pinned in `zano-keys.test.ts` (generated by the Zano CLI).
const ZANO_PLAIN =
  "mumble young surely very happiness quite men ball drive school rude against " +
  "ring salty fought nothing marry pale spot petal dart breast mother fruit jump goal";
const ZANO_SECURED =
  "stream approach people written bedroom waist high mist busy stranger inside " +
  "crash tide innocent canvas blame canvas put pity garden consider scary mask " +
  "stain shower self";
const ZANO_AUDITABLE =
  "describe choose peel sweat chain safe pale hurry insane honor shock shade " +
  "ashamed struggle surface rhyme eat make nobody sunlight thing them easily " +
  "dust jump heal";

/**
 * vec-1 from the P0 spike (`scratchpad/xelis-spike/vectors.json`): a 25-word
 * seed GENERATED BY `xelis_wallet` v1.25.0, which restored to
 * `xel:ym3qntl80esaae92u6ac4dk0nq2lle8scy03f8xknud9at29w3csqnyl7dc`.
 */
const XELIS_BINARY_SEED =
  "etched gypsy plywood guarded behind gels mighty mayor sulking pedantic dogs " +
  "asked badge having emit sniff godfather offend wonders biology niece railway " +
  "segments sieve behind";

// Detection only COUNTS words once BIP39 and Zano are ruled out, so these need
// only to be neither: "abducts" is a Monero-wordlist form in neither list.
const words = (n: number) => Array(n).fill("abducts").join(" ");

beforeEach(() => {
  xelisCheck.mockClear();
});

describe("detectSeedKind", () => {
  it("recognises a BIP39 phrase", () => {
    expect(detectSeedKind(BIP39)).toEqual({ kind: "bip39", ambiguous: false });
  });

  it("recognises a Zano seed with no passphrase", () => {
    expect(detectSeedKind(ZANO_PLAIN)).toEqual({
      kind: "zano",
      ambiguous: false,
      zanoPasswordProtected: false,
      zanoAuditable: false,
    });
  });

  it("flags a Secured-Seed Zano phrase as needing its passphrase", () => {
    const d = detectSeedKind(ZANO_SECURED);
    expect(d.kind).toBe("zano");
    expect(d.zanoPasswordProtected).toBe(true);
  });

  it("flags an auditable Zano seed, which cannot be derived", () => {
    const d = detectSeedKind(ZANO_AUDITABLE);
    expect(d.kind).toBe("zano");
    expect(d.zanoAuditable).toBe(true);
  });

  it("tolerates the whitespace a pasted Zano seed carries", () => {
    expect(detectSeedKind(`  ${ZANO_PLAIN.replace(/ /g, "   ")}\n`).kind).toBe("zano");
  });

  it("16 words that are not BIP39 or Zano are a Monero polyseed", () => {
    expect(detectSeedKind(words(16))).toEqual({ kind: "xmr", ambiguous: false });
  });

  it("25 words the Xelis check rejects are Monero-or-Zephyr — ambiguous, never auto-classified", () => {
    // Stubbed, not left to the real check: 25 copies of one word pass a real
    // Xelis checksum (the checksum word is that same word), so once the check
    // is implemented this phrase is Xelis-possible too.
    xelisCheck.mockReturnValueOnce({ ok: false, kind: "checksum" });
    expect(detectSeedKind(words(25))).toEqual({ kind: "xmr", ambiguous: true });
  });

  it("a 26-word phrase that is not a valid Zano seed is not Zano", () => {
    // Positive control for the Zano branch: word count alone must not pass it.
    expect(detectSeedKind(words(26)).kind).toBeNull();
  });

  it("rejects garbage and empties", () => {
    expect(detectSeedKind("")).toEqual({ kind: null, ambiguous: false });
    expect(detectSeedKind("not a seed at all").kind).toBeNull();
  });
});

/**
 * 2026-09-15. XELIS's English wordlist is Monero's, in the same order, and its
 * checksum word is chosen the same way, so a 25-word Xelis seed and a Monero or
 * Zephyr legacy seed cannot be told apart by their words. Restoring one as the
 * wrong coin opens a different, empty wallet with no error, so detection must
 * put Xelis beside Monero and Zephyr rather than pick one.
 */
describe("24 / 25 words: Xelis, Monero or Zephyr", () => {
  it("positive control: a binary-generated Xelis seed passes Monero's validator", async () => {
    // What makes the ambiguity real rather than a stub's say-so: this repo's
    // Monero checker, unmodified, accepts a seed `xelis_wallet` itself
    // generated. Measured in the spike too (identical wordlist and checksum).
    expect(await validateXmrSeed(XELIS_BINARY_SEED)).toEqual({ ok: true });
  });

  it("a phrase valid for Xelis and for Monero offers all three coins", () => {
    xelisCheck.mockReturnValueOnce({ ok: true });
    expect(detectSeedKind(XELIS_BINARY_SEED)).toEqual({
      kind: "xmr",
      ambiguous: true,
      xelisPossible: true,
    });
  });

  it("a 25-word phrase only the Xelis check accepts is Xelis", async () => {
    // Stands in for a seed in one of XELIS's ten other wordlists: the Monero
    // checksum fails because word 25 is not the checksum word.
    const notMonero = XELIS_BINARY_SEED.replace(/behind$/, "king");
    expect((await validateXmrSeed(notMonero)).ok).toBe(false);
    xelisCheck.mockReturnValueOnce({ ok: true });
    expect(detectSeedKind(notMonero)).toEqual({ kind: "xelis", ambiguous: false });
  });

  it("24 words the Xelis check accepts are Xelis alone", () => {
    // The binary accepts 24 words (the checksum is then unchecked); Monero and
    // Zephyr legacy seeds are always 25, so there is nothing to disambiguate.
    const twentyFour = XELIS_BINARY_SEED.split(" ").slice(0, 24).join(" ");
    xelisCheck.mockReturnValueOnce({ ok: true });
    expect(detectSeedKind(twentyFour)).toEqual({ kind: "xelis", ambiguous: false });
  });

  it("24 words the Xelis check rejects are not classified at all", () => {
    xelisCheck.mockReturnValueOnce({ ok: false, kind: "word-count", count: 24 });
    expect(detectSeedKind(words(24))).toEqual({ kind: null, ambiguous: false });
  });

  it("a Xelis check that throws classifies nothing as Xelis", () => {
    xelisCheck.mockImplementationOnce(() => {
      throw new Error("Xelis seed handling is not available in this build yet.");
    });
    expect(detectSeedKind(XELIS_BINARY_SEED)).toEqual({ kind: "xmr", ambiguous: true });
  });

  it("a Xelis checksum failure is not Xelis", () => {
    xelisCheck.mockReturnValueOnce({ ok: false, kind: "checksum" });
    expect(detectSeedKind(XELIS_BINARY_SEED)).toEqual({ kind: "xmr", ambiguous: true });
  });

  it("only 24- and 25-word phrases reach the Xelis check", () => {
    detectSeedKind(BIP39);
    detectSeedKind(ZANO_PLAIN);
    detectSeedKind(words(16));
    detectSeedKind(words(26));
    expect(xelisCheck).not.toHaveBeenCalled();
    detectSeedKind(XELIS_BINARY_SEED);
    detectSeedKind(words(24));
    expect(xelisCheck).toHaveBeenCalledTimes(2);
  });
});
