//! The typed boundary the swap-desk cryptography plugs into.
//!
//! # This file is a SEAM, not an implementation
//!
//! The real adaptor-signature and chain-leg cryptography for the ADA<>XMR/ZEPH
//! engine is a vendored Python library (`ed25519_adaptor.py`, `ada_leg.py`,
//! `xmr_leg.py`) that the desk itself does not reimplement — its Go engine
//! adapter bridges to that library over a JSON pipe and, in its own words,
//! "holds no crypto and no chain I/O of its own". Sub-plan 02 is explicit:
//!
//! > Do NOT hand-roll adaptor sigs / DLEq - lift verbatim.
//!
//! That instruction is load-bearing, not stylistic. Both sides of an atomic
//! swap must agree bit-for-bit on nonce derivation, challenge construction and
//! domain separation. A client that differs from the desk by one byte produces
//! a swap that locks real funds and can then neither claim NOR refund — and it
//! would pass every test written alongside it, because the same wrong
//! assumption authors both halves of the comparison. The `-dev` desk runs a
//! stub engine, so even a fully green conformance run proves nothing about
//! cryptographic agreement.
//!
//! So this module defines the OPERATIONS the protocol needs, with their exact
//! wire types from CONTRACT.md, and leaves the construction to whoever supplies
//! a real [`DeskCrypto`]. Everything around it — per-swap keygen at accept
//! time, encrypted persistence, the refund trigger — is real and tested.
//!
//! # Wire-format contract (CONTRACT.md section 2)
//!
//! - ed25519 points / pubkeys: 32 bytes, lowercase hex (64 chars).
//! - Adaptor pre-signature `{rEnc, sp}`: `rEnc` = R_enc 32B hex; `sp` = the
//!   pre-signature scalar reduced mod L, 32-byte **little-endian** hex.
//! - A spend scalar NEVER crosses the wire. Only points, pre-signatures, view
//!   secrets, txids and proofs do.
//!
//! # Swapping in the real provider
//!
//! Implement [`DeskCrypto`] (and [`RefundBroadcaster`]) over the vendored
//! library, return [`KeyProvenance::Vendored`], and change [`active_crypto`].
//! Nothing else in the desk tier needs to move.

#![allow(dead_code)] // the seam is wider than Stage A consumes

use std::time::Duration;
use zeroize::{Zeroize, ZeroizeOnDrop};

use super::engine::ClientRole;
use super::wire;

#[derive(Debug, thiserror::Error, PartialEq)]
pub enum CryptoError {
    /// The active provider cannot perform this operation. Carries the reason so
    /// the log names what is missing rather than "failed".
    #[error("desk crypto unavailable: {0}")]
    Unavailable(String),
    #[error("invalid key material: {0}")]
    InvalidMaterial(String),
    #[error("refund broadcast failed: {0}")]
    Broadcast(String),
    /// Raised when mock material reaches a path that moves value.
    #[error(
        "refusing to act on MOCK key material — this swap's keys were generated by the \
         Stage-A placeholder provider, not the real engine. Acting on them cannot recover funds."
    )]
    MockMaterialRefused,

    /// The ENGINE refused the call (`ok:false`, or a typed raise). A
    /// caller/theft-class rejection — a bad point, a pre-sig that does not bind,
    /// an out-of-order call, a guard that fired. **NEVER retried.**
    ///
    /// This variant exists because collapsing it into [`Self::Unavailable`]
    /// would throw away the distinction the transport works hard to preserve:
    /// `Unavailable` invites a retry or a respawn, and retrying a theft-class
    /// rejection is exactly the loop that must not exist.
    #[error("engine rejected {method}: {error_type}: {message}")]
    EngineRejected {
        method: String,
        error_type: String,
        message: String,
    },

    /// The sidecar cannot start with this configuration. Permanent — fix the
    /// config; do NOT respawn.
    #[error("engine sidecar configuration fault: {0}")]
    ConfigFault(String),

    /// C47d: the engine is HEALTHY AND BUSY — the call yielded or timed out
    /// waiting for the one serialized pipe and never reached the child.
    ///
    /// The transport has distinguished this from a hang since C32, and this seam
    /// — whose whole documented purpose is to preserve the transport's
    /// distinctions — was flattening it into [`Self::Unavailable`]. That is how
    /// one `Contended` on `set_lock_b_txid` read as "the engine did not answer"
    /// and killed a funded lane: the caller could not see that retrying was not
    /// just safe but the documented-correct response.
    #[error("engine busy: {method} yielded after {seconds}s without reaching the child")]
    EngineBusy { method: String, seconds: u64 },
}

/// Preserve the transport's error CLASS across the seam.
///
/// Found by running rung 2b's plumbing check: every sidecar failure was being
/// flattened to `Unavailable`, so a permanent engine rejection and a transient
/// death looked identical to callers. The transport distinguishes them
/// deliberately; this conversion is what keeps that distinction alive.
impl From<super::sidecar::SidecarError> for CryptoError {
    fn from(e: super::sidecar::SidecarError) -> Self {
        use super::sidecar::SidecarError as S;
        match e {
            S::EngineRejected {
                method,
                error_type,
                message,
            } => Self::EngineRejected {
                method,
                error_type,
                message,
            },
            S::BadConfig(m) | S::ConfigFault(m) => Self::ConfigFault(m),
            // C47d. Busy is not "did not answer" — the child never SAW the call.
            // Flattened, the one caller with a funded deadline behind it
            // (set_lock_b_txid, 2026-07-28) treated a queue-full moment as an
            // engine failure and died. Preserved, that caller retries.
            S::Contended { method, seconds } => Self::EngineBusy { method, seconds },
            // Spawn / Framing / Timeout / SidecarDied / BadResult are all
            // "the engine did not answer", which is retry-or-respawn territory.
            other => Self::Unavailable(other.to_string()),
        }
    }
}

impl CryptoError {
    /// True when retrying can never help (fix the config, or the engine has
    /// refused on the merits).
    pub fn is_permanent(&self) -> bool {
        matches!(
            self,
            Self::ConfigFault(_)
                | Self::EngineRejected { .. }
                | Self::MockMaterialRefused
                | Self::InvalidMaterial(_)
        )
    }

    /// True when the ENGINE refused on the merits. Never retry these.
    pub fn is_engine_rejection(&self) -> bool {
        matches!(self, Self::EngineRejected { .. })
    }

    /// C47d: true when the engine is healthy and busy — the one error class
    /// where an immediate bounded retry is the documented-correct response
    /// (the transport's own words: tearing down "would kill the work that was
    /// about to finish").
    pub fn is_transient_busy(&self) -> bool {
        matches!(self, Self::EngineBusy { .. })
    }
}

/// Where a swap's key material came from. Persisted with the swap so a refund
/// attempted later can tell whether the material is real.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyProvenance {
    /// Schema-shaped stand-ins. Protocol-conformant, cryptographically inert —
    /// exactly what the Go reference harness puts on the wire.
    Mock,
    /// Produced by the vendored engine library. Safe to act on.
    Vendored,
}

impl KeyProvenance {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Mock => "mock",
            Self::Vendored => "vendored",
        }
    }
    pub fn parse(s: &str) -> Self {
        match s {
            "vendored" => Self::Vendored,
            // Anything unrecognized is treated as mock — the SAFE default,
            // because mock material is refused rather than acted on.
            _ => Self::Mock,
        }
    }
    pub fn is_real(self) -> bool {
        matches!(self, Self::Vendored)
    }
}

/// Everything `init_swap` needs, assembled from the accept RESPONSE.
///
/// It is a context rather than three loose arguments because every field here
/// arrives together, in M1, and using a stale or hand-rolled value is the
/// funds-stranding class: these are the inputs that fix the canonical body.
pub struct SwapInitContext<'a> {
    /// The DESK-assigned swap id. Doubles as the sidecar's handle for this swap.
    pub swap_id: &'a str,
    pub role: ClientRole,
    pub pair: &'a str,
    pub amount_a: &'a str,
    pub amount_b: &'a str,
    pub t0: i64,
    pub t1: i64,
    pub t2: i64,
    /// The chain-A timelock slots FROM M1 — populated only when the DESK leads
    /// (SELL_FOLLOWER). When WE lead they are `None` and the engine derives them
    /// from the live chain tip, which is why the leader path needs chain access
    /// unless a caller supplies them. Never echo the desk's M1 slots when we
    /// lead: in BUY_FOLLOWER they are null by design (v8).
    pub t1_slot: Option<i64>,
    pub t2_slot: Option<i64>,
    /// The NEGOTIATED leader-proof capability — the desk's M1 answer verbatim.
    ///
    /// It belongs in this context for the reason the doc comment above gives:
    /// these are the inputs that fix the canonical body, and this one decides
    /// whether our refund-spend half is an OtVES adaptor or a plain signature.
    /// Taking it from anywhere other than M1 is the funds-stranding class —
    /// `ltc_swap.py:544` refuses to lock chain B when the record says the spend
    /// is plain, so a value that disagrees with the handshake strands the coin
    /// at the worst possible moment rather than failing the handshake.
    pub leader_proof: bool,
    /// The operator's nominated chain-A payout address — the SAME value sent to
    /// the desk in the accept.
    ///
    /// **This must reach OUR engine, because it changes the canonical claim body
    /// on BOTH sides.** `_canonical_claim_body` pays `st.bob.ada_dest`, and the
    /// engine sets that from `payout_address` when present, otherwise deriving
    /// `Address(vkey_hash(B_ada))`. So if the desk applies the nominated address
    /// and we derive, the two parties build DIFFERENT bodies, its claim pre-sig
    /// binds a txid we never construct, and our `adaptor_verify` refuses — which
    /// is exactly what happened to swap `46d85388` once the desk shipped its half
    /// of the D16 wiring (`64ef434`) and ours was still missing.
    ///
    /// The failure is loud and safe — the follower refuses to complete rather than
    /// submitting a claim that pays somewhere it did not intend — but it strands
    /// the swap to T1. Empty is a valid value and means "derive", which is what
    /// both sides did before the wiring existed.
    pub payout_address: &'a str,

    /// The operator's nominated chain-A **refund** address — the same value sent
    /// to the desk in the accept, and the exact mirror of `payout_address` above.
    ///
    /// **It must reach OUR engine for the same reason, one field over.** The
    /// refund body pays `st.alice.ada_dest`. Until the desk's D25 that was derived
    /// unconditionally on both sides, so both agreed and nobody noticed. D25 made
    /// it nominatable and ownership-keyed — which fixed THEIR derivation and left
    /// ours deriving, so the two refund bodies stopped matching and the desk's
    /// refund pre-signature could no longer `adaptor_verify`.
    ///
    /// Caught at M3 on the first drive after their fix, with nothing on chain: we
    /// refuse to submit a lock whose refund we could not complete at T1. That is
    /// the safe direction, and it is still a stranded drive.
    ///
    /// **This is C12 a second time.** Same engine, same class of field, one input
    /// present on one side. The lesson the first instance was supposed to teach is
    /// that a nominatable destination has TWO halves, and shipping either alone
    /// breaks agreement — so when the counterparty makes a value nominatable, that
    /// is the moment to send it, not to note that they did.
    pub refund_address: &'a str,
}

/// Per-swap key material, generated ONCE just after accept.
///
/// The non-custody invariant in type form. Note what is NOT here: the spend
/// scalar. The sidecar mints and keeps it in its OWN encrypted store, addressed
/// by [`engine_ref`](Self::engine_ref) — so the secret never enters Rust at all,
/// and there is no field that could leak into a log, the webview, or the wire.
/// That is stronger than the earlier design, which held the scalar in Rust and
/// relied on `ZeroizeOnDrop` plus discipline to keep it contained.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct SwapKeyMaterial {
    /// The client's key-share POINT. Sent in M2.
    pub client_key_share_point: String,
    /// The client's chain-A pubkey. Sent in M2 (never in the accept request —
    /// the desk does not read it there; see `DESK-ANSWER-v6.md` Q1).
    pub client_chain_a_pubkey: String,
    /// Adaptor point T. Present only when the CLIENT is the follower
    /// (SELL_FOLLOWER); the desk supplies it in M1 when it follows.
    ///
    /// **CLIENT-1 widens this on the LTC leg:** when we LEAD there with the
    /// leader-proof capability on, we also carry an adaptor point - and it is
    /// READ OUT OF [`dleq_proof`](Self::dleq_proof) by the engine, never
    /// derived beside it. A point supplied next to a proof is a point nobody
    /// proved anything about.
    pub adaptor_point: Option<String>,
    /// CLIENT-1: the cross-group DLEAG proof binding our chain-B share to a
    /// secp256k1 point, when this leg needs one.
    ///
    /// `None` on ADA in BOTH directions - both legs are edwards25519, so there
    /// is no cross-group statement to make and a proof here would signal
    /// cross-curve to the desk. `None` on LTC too unless the swap negotiated
    /// the capability, because an unasked-for proof is refused rather than
    /// ignored.
    pub dleq_proof: Option<String>,
    /// Shared view secret for the XMR/ZEPH joint address. Secret-ish: it grants
    /// visibility, not spend authority. The one allowlisted secret on the wire.
    pub view_key: Option<String>,
    /// Handle to the sidecar's own encrypted state for this swap. The SECRET
    /// lives there, not here.
    pub engine_ref: String,
    /// Chain-A refund timelock slot, committed by the LEADER. Present only when
    /// the CLIENT leads (BUY_FOLLOWER) — the exact mirror of `adaptor_point` /
    /// `view_key`, which are FOLLOWER material. When we follow, the desk
    /// committed the slots in M1 and we leave these `None`. Public, not secret,
    /// so not zeroized.
    #[zeroize(skip)]
    pub t1_slot: Option<i64>,
    /// Chain-A swipe timelock slot. Same leader-only rule as `t1_slot`.
    #[zeroize(skip)]
    pub t2_slot: Option<i64>,
    #[zeroize(skip)]
    pub provenance: KeyProvenance,
}

impl SwapKeyMaterial {
    /// The subset that may legitimately be sent to the desk in M2.
    pub fn keys_request(&self) -> wire::KeysRequest {
        wire::KeysRequest {
            client_key_share_point: self.client_key_share_point.clone(),
            client_chain_a_pubkey: self.client_chain_a_pubkey.clone(),
            adaptor_point: self.adaptor_point.clone(),
            view_key: self.view_key.clone(),
            // CLIENT-1. This was hardcoded `None` with an ADA-shaped reason:
            // "ADA and XMR/ZEPH are both edwards25519 - same curve, no DLEq."
            // True for ADA forever, and wrong for LTC, where chain A is
            // secp256k1 and the cross-group proof is what binds our chain-B
            // share to the point the counterparty encrypts under.
            //
            // The value comes from the ENGINE, which emits it only when this
            // leg needs one and the swap negotiated the capability - so a leg
            // that has no proof still sends `null` here and the ADA wire is
            // byte-identical to what has always settled.
            dleq_proof: self.dleq_proof.clone(),
            // LEADER material: set only when WE lead, so the desk-as-follower can
            // derive the same chain-A script address to watch our lock at.
            t1_slot: self.t1_slot,
            t2_slot: self.t2_slot,
        }
    }
}

/// Context a refund pre-signature is produced against.
pub struct RefundSignContext<'a> {
    pub swap_id: &'a str,
    pub pair: &'a str,
    pub direction: &'a str,
    /// Where the reclaimed funds go.
    pub refund_address: &'a str,
    /// Absolute T1 (unix seconds) — the refund branch is only valid after it.
    pub t1_unix: i64,
}

/// The counterparty's M1/M2 public contribution, as we hand it to the engine.
pub struct CounterpartyKeys<'a> {
    pub key_share_point: &'a str,
    pub chain_a_pubkey: &'a str,
    pub adaptor_point: Option<&'a str>,
    pub view_key: Option<&'a str>,
    pub dleq_proof: Option<&'a str>,
    /// The LEADER's committed chain-A slots. Populated only when the
    /// COUNTERPARTY leads (i.e. we follow) — the desk sends them in M1.
    pub t1_slot: Option<i64>,
    pub t2_slot: Option<i64>,
    /// CC-24 / F32-0: the destinations the COUNTERPARTY nominates for its own
    /// chain-A proceeds, taken from M1.
    ///
    /// `None` means "not nominated", and the engine then derives as it always
    /// has — which is both the compatibility path for a desk that has not
    /// shipped this yet and the fallback the desk's own FALSIFY requires.
    /// An empty string is never a destination; `commands::opt_nonempty` is
    /// what turns the wire's `""` into `None`.
    pub claim_dest: Option<&'a str>,
    pub refund_dest: Option<&'a str>,
}

/// What the engine derives once both halves are in: the 2-of-2 joint key and
/// the two lock addresses.
#[derive(Debug, Clone, PartialEq)]
pub struct JointKeys {
    pub chain_a_lock_addr: String,
    pub chain_b_joint_key: String,
    pub chain_b_joint_addr: String,
}

/// The active crypto provider.
///
/// This is an ENUM rather than `&dyn DeskCrypto` on purpose. The vendored
/// provider's operations are `async` (they are round-trips to the sidecar), and
/// async fns are not object-safe: `dyn` would need the `async-trait` crate, and
/// `Cargo.toml` is a permission-gated file here. Enum dispatch costs nothing,
/// keeps the swap-in point explicit, and is honest — there are exactly two
/// providers and there is no plugin story.
pub enum ActiveCrypto {
    /// Schema-shaped stand-ins. Protocol-conformant, cryptographically inert.
    Mock(MockDeskCrypto),
    /// The real vendored engine, driven over the stdio sidecar.
    Vendored(VendoredDeskCrypto),
}

impl ActiveCrypto {
    pub fn provenance(&self) -> KeyProvenance {
        match self {
            Self::Mock(_) => KeyProvenance::Mock,
            Self::Vendored(_) => KeyProvenance::Vendored,
        }
    }

    /// Mint this swap's key material. Runs AFTER accept, keyed on the
    /// desk-assigned swap id (see [`SwapInitContext`]).
    pub async fn generate_swap_keys(
        &self,
        ctx: &SwapInitContext<'_>,
    ) -> Result<SwapKeyMaterial, CryptoError> {
        match self {
            Self::Mock(m) => m.generate_swap_keys(ctx),
            Self::Vendored(v) => v.generate_swap_keys(ctx).await,
        }
    }

    /// Feed the counterparty's half in, forming the 2-of-2 joint key + the lock
    /// addresses. Rejects a torsion/small-order point or a wrong role shape.
    pub async fn ingest_counterparty(
        &self,
        swap_id: &str,
        cp: &CounterpartyKeys<'_>,
    ) -> Result<JointKeys, CryptoError> {
        match self {
            Self::Mock(m) => m.ingest_counterparty(swap_id, cp),
            Self::Vendored(v) => v.ingest_counterparty(swap_id, cp).await,
        }
    }
}

/// The result of an `extract_secret` call, with the `false` case classified.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecretExtraction {
    pub secret_held: bool,
    pub reason: String,
}

/// Whether the chain-A lock has been spent, and by what.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SpendSighting {
    /// The lock was spent by this transaction. Feed the txid to
    /// [`VendoredDeskCrypto::extract_secret`], which binds it independently.
    Spent { txid: String },
    /// We looked; the lock is still unspent.
    NotSpent,
    /// We could not look. NOT "not spent" — read as that, the whole discovery
    /// path goes quiet at exactly the moment it is needed.
    CouldNotLook { error: String },
}

impl SpendSighting {
    /// Same ordering rule as the lock watcher: a populated `error` wins over
    /// `spent:false`, because that `false` is the fail-soft default rather than
    /// an observation. A `spent:true` with no txid is treated as could-not-look
    /// — there is nothing to hand to `extract_secret`, so claiming a spend was
    /// seen would only produce a confusing failure one step later.
    pub fn from_engine(v: &serde_json::Value) -> Self {
        let err = v.get("error").and_then(|e| e.as_str()).unwrap_or("").trim();
        let spent = v
            .get("spent")
            .and_then(serde_json::Value::as_bool)
            .unwrap_or(false);
        let txid = v
            .get("txid")
            .and_then(|t| t.as_str())
            .unwrap_or("")
            .trim()
            .to_string();

        if !err.is_empty() && !spent {
            return Self::CouldNotLook {
                error: err.to_string(),
            };
        }
        if spent {
            if txid.is_empty() {
                return Self::CouldNotLook {
                    error: "the engine reported the lock spent but named no spending tx".into(),
                };
            }
            return Self::Spent { txid };
        }
        Self::NotSpent
    }
}

/// What a `false` from `extract_secret` actually means.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExtractionOutlook {
    /// The engine holds the scalar. Proceed.
    Held,
    /// Not visible yet, or a transient read failure. Retry the SAME txid.
    RetryLater,
    /// This txid does not carry the swap's secret — a wrong or hostile one.
    /// Permanent **for that txid, not for the swap**: a different transaction
    /// may still be the real refund. So the response is not "give up" and not
    /// "retry this"; it is *keep discovering*.
    ///
    /// This state exists because of engine v11's A5 fix. Before it,
    /// `extract_secret` computed `s - sp`, stored it and reported success
    /// without checking the result was the swap's secret — so any transaction
    /// signed by the same vkey yielded `secretHeld: true` and garbage. The
    /// binding is what makes a wrong txid produce a refusal instead.
    WrongTxid,
    /// This backend can never extract. Retrying is a loop that never ends, and
    /// the coin needs a human.
    Impossible,
    /// C38: the counterparty took chain A via **B3, the after-T2 deep-abort
    /// swipe**, so `s_a` was never published and never will be.
    ///
    /// The script's three branches are `B1 = [sigA, sigB]`, `B2 = [after T1,
    /// sigA, sigB]`, `B3 = [after T2, sigA]`. All three need the leader's
    /// signature and **only B3 omits the follower's**, so a confirmed spend
    /// carrying the leader's vkey witness and not the follower's can only be B3
    /// — one witness where the cooperative paths need two.
    ///
    /// It matters because B3 is signed with an ORDINARY signature, not an
    /// adaptor one, so it leaks nothing. A follower waiting for `s_a` after a
    /// swipe is waiting for something that will never be published.
    ///
    /// **Deliberately NOT folded into [`Impossible`]**, which they superficially
    /// resemble — both mean "stop retrying". They need different humans doing
    /// different things: `Impossible` is a CONFIG fault on our side (a backend
    /// that cannot extract, fix the deployment), while `Swiped` is a PROTOCOL
    /// outcome on the chain (the counterparty deep-aborted; our chain-B coin is
    /// unrecoverable without them volunteering their key share). Collapsing them
    /// would send someone to check their engine config over a coin that is gone.
    Swiped,
}

impl SecretExtraction {
    /// Classify. Anything unrecognized is [`ExtractionOutlook::RetryLater`] —
    /// the safe default, because it neither gives up on a recoverable coin nor
    /// declares an unrecoverable one recovered.
    pub fn outlook(&self) -> ExtractionOutlook {
        if self.secret_held {
            return ExtractionOutlook::Held;
        }
        if self.reason.starts_with("unsupported-backend") {
            return ExtractionOutlook::Impossible;
        }
        // C38 / desk D37. Matched on the engine's own marker literal, which
        // `desk_engine.py:88` defines as `SWIPE_MARKER = "SWIPED (B3"` and builds
        // `SWIPE_REASON` from — so the string is the contract across the language
        // boundary, exactly as the desk pins it with
        // `TestSwipeMarkerMatchesTheEngineLiteral`.
        //
        // Checked BEFORE the fallthrough because the fallthrough is `RetryLater`,
        // and that default — correct for an UNKNOWN reason — is the wrong answer
        // for a KNOWN terminal one. Without this arm we poll forever over a coin
        // that is provably gone, which is the whole of D37.
        if self.reason.contains("SWIPED (B3") {
            return ExtractionOutlook::Swiped;
        }
        // The A5 refusal. Matched on the distinctive phrase rather than the
        // whole sentence so a reworded message still classifies; if it ever
        // stops matching, the fallback is RetryLater, which keeps looking — the
        // safe direction.
        if self.reason.contains("does not carry the swap's secret") {
            return ExtractionOutlook::WrongTxid;
        }
        ExtractionOutlook::RetryLater
    }
}

/// Everything needed to publish a refund, assembled from the persisted record.
pub struct RefundRequest<'a> {
    pub swap_id: &'a str,
    pub pair: &'a str,
    pub direction: &'a str,
    pub refund_address: &'a str,
    /// The pre-signature captured at M3, before the lock.
    pub refund_presig: wire::AdaptorPresig,
    /// Which chain leg the client locked and is reclaiming ("A" or "B").
    pub chain: &'a str,
    pub lock_txid: &'a str,
    pub provenance: KeyProvenance,
}

/// Publishes the refund transaction to the chain the client locked on.
///
/// The future is boxed by hand rather than via `async-trait`, for the same
/// reason [`ActiveCrypto`] is an enum: an `async fn` in a trait is not
/// object-safe, and this trait exists precisely so tests can inject a spy in
/// place of the real broadcaster. Boxing keeps `&dyn RefundBroadcaster` working
/// while the real implementation does chain I/O.
pub type BroadcastFuture<'a> =
    std::pin::Pin<Box<dyn std::future::Future<Output = Result<String, CryptoError>> + Send + 'a>>;

pub trait RefundBroadcaster: Send + Sync {
    fn broadcast_refund<'a>(&'a self, req: &'a RefundRequest<'a>) -> BroadcastFuture<'a>;
}

// ─────────────────────────── Stage-A providers ───────────────────────────

/// Deterministic, schema-shaped stand-ins — the same discipline the Go
/// reference harness uses (`mockHex`). Protocol-conformant and
/// cryptographically INERT: it satisfies the wire format so the state machine,
/// the persistence and the gating can all be exercised end to end, and nothing
/// it produces can move a coin.
pub struct MockDeskCrypto;

/// Stand-in chain-A timelock slots for the mock leader path. Only the ordering
/// (`t2 > t1 > 0`) is load-bearing — that is what the desk's `set_lock_slots`
/// sanity-checks. The real provider derives these from the chain tip inside
/// `init_swap(role=LEADER)`.
/// Timeout for engine calls that REBUILD AND RESCAN a Monero wallet.
///
/// `reclaim` (and the leader's `claim`) go through `restore_joint_and_sweep`:
/// `generate_from_keys` to rebuild the joint wallet, `refresh` to scan stagenet
/// from the restore height, then `sweep_all`. That is minutes of work — the
/// desk's equivalent sweep took 2m3s — against the sidecar's 30s default, so the
/// reclaim could never complete. Observed 2026-07-26: it timed out at 30s twice
/// while the Python side kept scanning, which also desynchronises the sidecar's
/// request/response ids (`expected id 18, got Some(15)`) because the late reply
/// arrives against the next call.
///
/// Deliberately NOT applied to the `watch_*` pollers. For a poll loop, failing
/// fast and retrying is correct; blocking one for fifteen minutes would blind
/// every gate that reads it.
const WALLET_RESTORE_TIMEOUT: Duration = Duration::from_secs(900);

/// C47: the watch lane's read budget, sized so a cold chain-B watch COMPLETES.
///
/// The measured worst case is ~128s (open_wallet ~4s + full-scan refresh ~124s,
/// desk 2026-07-28), and the old budget was `DEFAULT_CALL_TIMEOUT` = 30s. A
/// watcher that gives up mid-restore does not cancel anything — the line
/// protocol cannot — it abandons an in-flight request, desyncs the pipe, and
/// the respawn re-runs the same restore into the same too-small budget. That
/// loop keeps the engine permanently mid-restore and answers nobody, which is
/// strictly worse than one slow poll. Watchers are background by definition:
/// they can afford to wait, and since C47a they wait holding no one's slot.
///
/// The trade, stated: while a cold watch holds the pipe, a protocol call queues
/// behind it for up to this long. That is the pre-warm argument (Start-Stack
/// opens both wallets before any drive), not a reason to re-shrink the budget —
/// shrinking recreates the thrash that starved the 2026-07-28 BUY lane.
const WATCH_CALL_TIMEOUT: Duration = Duration::from_secs(300);

const MOCK_T1_SLOT: i64 = 84_600_000;
const MOCK_T2_SLOT: i64 = 84_603_600;

fn mock_hex(parts: &[&str]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(b"pwnda-desk-mock-v1");
    for p in parts {
        h.update(b"|");
        h.update(p.as_bytes());
    }
    hex::encode(h.finalize())
}

impl MockDeskCrypto {
    pub fn provenance(&self) -> KeyProvenance {
        KeyProvenance::Mock
    }

    /// Deterministic stand-ins. Mirrors the real provider's SHAPE exactly —
    /// including the role flips — so the state machine, persistence and gating
    /// are exercised identically; nothing it returns can move a coin.
    pub fn generate_swap_keys(
        &self,
        ctx: &SwapInitContext<'_>,
    ) -> Result<SwapKeyMaterial, CryptoError> {
        let (context_id, role, pair) = (ctx.swap_id, ctx.role, ctx.pair);
        if context_id.is_empty() {
            return Err(CryptoError::InvalidMaterial("empty context id".into()));
        }
        // The adaptor point + view key are the FOLLOWER's contribution. When the
        // client leads, the desk supplies both in M1 and the client must send
        // null - see the role flip in [[swap-desk-protocol]].
        let is_follower = role == ClientRole::Follower;
        Ok(SwapKeyMaterial {
            client_key_share_point: mock_hex(&[pair, context_id, "keyshare-point"]),
            client_chain_a_pubkey: mock_hex(&[pair, context_id, "chain-a-pubkey"]),
            adaptor_point: is_follower.then(|| mock_hex(&[pair, context_id, "adaptor-T"])),
            view_key: is_follower.then(|| mock_hex(&[pair, context_id, "view-key"])),
            // The mock drives the ADA leg, which has no cross-group proof in
            // either direction. Deliberately NOT a mock_hex: a placeholder here
            // would make every ADA fixture carry a proof and quietly satisfy
            // the leg-aware assertions that exist to refuse exactly that.
            dleq_proof: None,
            // No secret here: the mock has no sidecar, so its handle is just the
            // swap id. The real provider returns the engine's own `engineRef`.
            engine_ref: context_id.to_string(),
            // The OPPOSITE flip from the adaptor/view pair: the chain-A timelock
            // slots are LEADER material, so they are set only when we lead. A
            // leader echoes back whatever slots it was given, else the fixed
            // stand-ins; the real engine derives them from the live chain tip.
            t1_slot: (!is_follower).then(|| ctx.t1_slot.unwrap_or(MOCK_T1_SLOT)),
            t2_slot: (!is_follower).then(|| ctx.t2_slot.unwrap_or(MOCK_T2_SLOT)),
            provenance: KeyProvenance::Mock,
        })
    }

    /// Shape-only joint-key formation. Deterministic in both halves so the two
    /// sides of a mock swap agree, mirroring the real engine's property.
    pub fn ingest_counterparty(
        &self,
        swap_id: &str,
        cp: &CounterpartyKeys<'_>,
    ) -> Result<JointKeys, CryptoError> {
        if cp.key_share_point.len() != 64 || cp.chain_a_pubkey.len() != 64 {
            return Err(CryptoError::InvalidMaterial(
                "counterparty points must be 32-byte hex".into(),
            ));
        }
        Ok(JointKeys {
            chain_a_lock_addr: format!("addr_mock_{}", &mock_hex(&[swap_id, "lockA"])[..16]),
            chain_b_joint_key: mock_hex(&[swap_id, cp.key_share_point, "jointB"]),
            chain_b_joint_addr: format!("xmr_mock_{}", &mock_hex(&[swap_id, "jointBaddr"])[..16]),
        })
    }

    /// M3. Deferred to rung 2b for the vendored path: the real
    /// `exchange_refund_sigs` needs read-only chain access (the fee estimate
    /// fixes the canonical txid the pre-sig binds).
    pub fn presign_refund(
        &self,
        _material: &SwapKeyMaterial,
        ctx: &RefundSignContext<'_>,
    ) -> Result<wire::AdaptorPresig, CryptoError> {
        Ok(wire::AdaptorPresig {
            r_enc: mock_hex(&[ctx.swap_id, "refund-rEnc"]),
            sp: mock_hex(&[ctx.swap_id, "refund-sp"]),
        })
    }

    /// M3 verify. Same rung-2b deferral as [`Self::presign_refund`].
    pub fn verify_presig(
        &self,
        presig: &wire::AdaptorPresig,
        _ctx: &RefundSignContext<'_>,
    ) -> Result<(), CryptoError> {
        // Shape-only. A real provider verifies the adaptor equation and
        // subgroup-validates every incoming point (`valid_subgroup_point`).
        let ok = |s: &str| s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit());
        if ok(&presig.r_enc) && ok(&presig.sp) {
            Ok(())
        } else {
            Err(CryptoError::InvalidMaterial(
                "presig fields must be 32-byte hex".into(),
            ))
        }
    }
}

// ─────────────────────── the vendored (real) provider ───────────────────────

/// The real engine, driven over the [`EngineSidecar`] stdio transport.
///
/// This holds NO crypto of its own — it marshals JSON to `desk_helper.py` and
/// back, which is exactly the "lift verbatim" contract: the same Python the desk
/// runs, with our role. Every operation here is one line-delimited round-trip.
pub struct VendoredDeskCrypto {
    sidecar: super::sidecar::EngineSidecar,
}

/// Pull a required string out of an engine result, naming the field when absent
/// so a protocol drift reads as "the engine did not send X", not "None".
fn req_str(v: &serde_json::Value, key: &str, method: &str) -> Result<String, CryptoError> {
    v.get(key)
        .and_then(|x| x.as_str())
        .map(str::to_string)
        .ok_or_else(|| {
            CryptoError::InvalidMaterial(format!("{method}: engine result is missing `{key}`"))
        })
}

fn opt_str(v: &serde_json::Value, key: &str) -> Option<String> {
    v.get(key).and_then(|x| x.as_str()).map(str::to_string)
}

fn opt_i64(v: &serde_json::Value, key: &str) -> Option<i64> {
    v.get(key).and_then(|x| x.as_i64())
}

impl VendoredDeskCrypto {
    pub fn new(sidecar: super::sidecar::EngineSidecar) -> Self {
        Self { sidecar }
    }

    /// `init_swap` — our M1/M2 public contribution. The SECRET stays in the
    /// sidecar's encrypted store; we get back only points plus the handle.
    ///
    /// Slots: when we FOLLOW we pass the desk's M1 slots straight through; when
    /// we LEAD we pass whatever the caller supplied (usually nothing) and the
    /// engine derives them from the live chain tip — which is why the
    /// unsupplied-leader path needs chain access. Either way we read the
    /// authoritative slots back OUT of the result, never off the desk's M1.
    pub async fn generate_swap_keys(
        &self,
        ctx: &SwapInitContext<'_>,
    ) -> Result<SwapKeyMaterial, CryptoError> {
        let mut params = serde_json::json!({
            "swapId": ctx.swap_id,
            "role": match ctx.role {
                ClientRole::Leader => "LEADER",
                ClientRole::Follower => "FOLLOWER",
            },
            "pair": ctx.pair,
            "amountA": ctx.amount_a,
            "amountB": ctx.amount_b,
            "t0": ctx.t0,
            "t1": ctx.t1,
            "t2": ctx.t2,
            "payoutAddress": ctx.payout_address,
            // D22. The engine derives the claim destination from who OWNS this
            // value, not from the reader's role — because the same engine code runs
            // on both sides and role cannot distinguish the two deployments.
            //
            // `false` because this is OUR payout address, not the counterparty's.
            // The desk's coordinator sends the counterparty's, so the field defaults
            // to `true` and its behaviour is unchanged. Omitting it here does not
            // fail quietly: the engine refuses init_swap outright ("payoutAddress is
            // owned by the LEADER, which is not us"), which is why this is a
            // one-line change and not a silent-corruption class.
            "payoutIsCounterparty": false,
            // D25's client half, and it is C12 again one field over.
            //
            // The desk made the refund destination nominatable and ownership-keyed,
            // exactly as it had already done for the payout. That fixes THEIR
            // derivation — and leaves ours deriving unless we send the same value,
            // which is precisely the shape that cost swap 46d85388: same engine,
            // same function, one input present on one side.
            //
            // Caught at M3 on the first drive after their fix landed: their refund
            // body paid our nominated address, ours paid the derived one, so the
            // pre-signature could not adaptor_verify. Nothing reached a chain.
            //
            // `false` because this is OUR refund address, not the counterparty's —
            // the mirror of the payout flag directly above.
            "refundAddress": ctx.refund_address,
            "refundIsCounterparty": false,
        });
        // Only send the slot keys when we actually have values: an explicit
        // null would be indistinguishable from "derive", and 0 is what v8 stopped
        // sending precisely because it is not a slot.
        if let (Some(o), Some(t1)) = (params.as_object_mut(), ctx.t1_slot) {
            o.insert("t1Slot".into(), t1.into());
        }
        if let (Some(o), Some(t2)) = (params.as_object_mut(), ctx.t2_slot) {
            o.insert("t2Slot".into(), t2.into());
        }
        // CLIENT-1 / C31-2. Sent UNCONDITIONALLY, unlike the slot keys above,
        // because absent and false are the same thing to the engine
        // (`bool(p.get("leaderProof"))` at desk_helper.py:518) while absent and
        // "derive it yourself" are different things for a slot. Sending it
        // always also means the engine's record and M1 can be compared after the
        // fact without knowing which client version opened the swap.
        if let Some(o) = params.as_object_mut() {
            o.insert("leaderProof".into(), ctx.leader_proof.into());
        }

        let r = self
            .sidecar
            .call("init_swap", params)
            .await
            .map_err(CryptoError::from)?;

        let is_follower = ctx.role == ClientRole::Follower;
        let material = SwapKeyMaterial {
            client_key_share_point: req_str(&r, "keySharePoint", "init_swap")?,
            client_chain_a_pubkey: req_str(&r, "chainAPubkey", "init_swap")?,
            adaptor_point: opt_str(&r, "adaptorPoint"),
            // CLIENT-1: present only when the engine was opened with the
            // leader-proof capability AND this leg has one. Absent is the
            // normal case and means "no proof", never "an empty proof".
            dleq_proof: opt_str(&r, "dleqProof"),
            view_key: opt_str(&r, "viewKey"),
            engine_ref: opt_str(&r, "engineRef").unwrap_or_else(|| ctx.swap_id.to_string()),
            // LEADER material. We take these from OUR OWN init_swap result (Q2),
            // never from the desk's M1 — when we lead, its M1 slots are null.
            t1_slot: (!is_follower).then(|| opt_i64(&r, "t1Slot")).flatten(),
            t2_slot: (!is_follower).then(|| opt_i64(&r, "t2Slot")).flatten(),
            provenance: KeyProvenance::Vendored,
        };

        // Fail closed on the role contract rather than sending a malformed M2.
        // These mirror the engine's own checks; catching them here names the
        // problem at the seam instead of as a rejected message.
        if is_follower {
            if material.adaptor_point.is_none() || material.view_key.is_none() {
                return Err(CryptoError::InvalidMaterial(
                    "init_swap(FOLLOWER) returned no adaptorPoint/viewKey - the follower must \
                     contribute both in M2"
                        .into(),
                ));
            }
        } else {
            match (material.t1_slot, material.t2_slot) {
                (Some(t1), Some(t2)) if t2 > t1 && t1 > 0 => {}
                _ => {
                    return Err(CryptoError::InvalidMaterial(format!(
                        "init_swap(LEADER) returned unusable timelock slots (t1={:?}, t2={:?}); \
                         the leader commits the chain-A refund window, so t2 > t1 > 0 is required",
                        material.t1_slot, material.t2_slot
                    )))
                }
            }
        }
        Ok(material)
    }

    /// `ingest_counterparty` — form the 2-of-2 joint key + the lock addresses.
    ///
    /// `ok:false` here is a torsion/small-order point or a wrong role shape. It
    /// is a theft-class rejection, so it surfaces as an error and is NEVER
    /// retried (the transport enforces that distinction too).
    pub async fn ingest_counterparty(
        &self,
        swap_id: &str,
        cp: &CounterpartyKeys<'_>,
    ) -> Result<JointKeys, CryptoError> {
        let mut params = serde_json::json!({
            "swapId": swap_id,
            "keySharePoint": cp.key_share_point,
            "chainAPubkey": cp.chain_a_pubkey,
            "adaptorPoint": cp.adaptor_point,
            "viewKey": cp.view_key,
            "dleqProof": cp.dleq_proof,
        });
        // The counterparty's slots, present only when THEY lead (we follow).
        if let (Some(o), Some(t1)) = (params.as_object_mut(), cp.t1_slot) {
            o.insert("t1Slot".into(), t1.into());
        }
        if let (Some(o), Some(t2)) = (params.as_object_mut(), cp.t2_slot) {
            o.insert("t2Slot".into(), t2.into());
        }

        let r = self
            .sidecar
            .call("ingest_counterparty", params)
            .await
            .map_err(CryptoError::from)?;

        // `ok:false` is a structured refusal WITH a reason, not an error frame.
        if r.get("ok").and_then(|v| v.as_bool()) != Some(true) {
            let reason = opt_str(&r, "reason").unwrap_or_else(|| "no reason given".into());
            return Err(CryptoError::InvalidMaterial(format!(
                "engine refused the counterparty material: {reason}"
            )));
        }
        Ok(JointKeys {
            chain_a_lock_addr: req_str(&r, "chainALockAddr", "ingest_counterparty")?,
            chain_b_joint_key: req_str(&r, "chainBJointKey", "ingest_counterparty")?,
            chain_b_joint_addr: req_str(&r, "chainBJointAddr", "ingest_counterparty")?,
        })
    }

    /// Record the realized chain-A lock UTxO. **Precondition for M3**: without
    /// it `exchange_refund_sigs` refuses (`no lock UTxO recorded yet`), because
    /// the refund body is built over this exact input.
    pub async fn set_lock_utxo(
        &self,
        swap_id: &str,
        txid: &str,
        index: i64,
        amount: &str,
    ) -> Result<(), CryptoError> {
        self.sidecar
            .call(
                "set_lock_utxo",
                serde_json::json!({
                    "swapId": swap_id, "txid": txid, "index": index, "amount": amount,
                }),
            )
            .await
            .map(|_| ())
            .map_err(CryptoError::from)
    }

    /// The chain-A destination OUR engine will build the claim body over.
    ///
    /// Read from the engine's own `status`, which since D20 derives it through the
    /// single `_claim_dest` used by the body builder itself — so what we read here
    /// is what we would sign, not a second derivation that could drift from it.
    ///
    /// Exists to be compared against the desk's published `claimDest` **before we
    /// lock chain B**. Empty means the engine has no view yet.
    pub async fn claim_dest(&self, swap_id: &str) -> Result<String, CryptoError> {
        let v = self
            .sidecar
            .call("status", serde_json::json!({ "swapId": swap_id }))
            .await
            .map_err(CryptoError::from)?;
        Ok(v.get("claimDest")
            .and_then(|d| d.as_str())
            .unwrap_or_default()
            .to_string())
    }

    /// The chain-A destination OUR engine will build the REFUND body to.
    ///
    /// Sibling of [`Self::claim_dest`], read the same way and for the same reason:
    /// what the body builder itself would use, not a second derivation that could
    /// drift from it. Empty means the engine has no view yet.
    pub async fn refund_dest(&self, swap_id: &str) -> Result<(String, String), CryptoError> {
        let v = self
            .sidecar
            .call("status", serde_json::json!({ "swapId": swap_id }))
            .await
            .map_err(CryptoError::from)?;
        let get = |k: &str| {
            v.get(k)
                .and_then(|d| d.as_str())
                .unwrap_or_default()
                .to_string()
        };
        Ok((get("refundDest"), get("refundDestSource")))
    }

    /// **LEADER, phase 1 of 2.** Build and sign our own chain-A lock, record its
    /// deterministic UTxO, and do **NOT** submit it. Returns the built output.
    ///
    /// This is the client half of prepare-and-share, mirrored for BUY_FOLLOWER
    /// (where we lead). The ordering it exists to make possible is:
    ///
    /// ```text
    ///   prepare_lock  ->  share the UTxO with the desk  ->  M3  ->  submit_lock
    /// ```
    ///
    /// and every step of that order is load-bearing. The desk-as-follower builds
    /// its refund pre-signature **over this exact input**, so it must learn the
    /// UTxO before M3; and we must hold its verified pre-signature before the
    /// lock goes on chain, or we would have funds locked in a script with no
    /// counter-signed way out. Submitting first and sharing after is the shape
    /// that strands a leg.
    ///
    /// Why a separate call rather than `lock`: the engine's `lock` RPC takes the
    /// leader branch straight through `prepare_and_lock_ada`, i.e. prepare AND
    /// submit in one round-trip, leaving no seam for the share and M3 in between.
    /// SELL never needed the split because there the DESK leads.
    ///
    /// Moves nothing. Idempotent — a second call returns the already-recorded
    /// UTxO rather than building a second transaction, which matters because a
    /// re-prepare could select different funding inputs and silently invalidate a
    /// pre-signature the counterparty is already holding (the desk's D17).
    ///
    /// Funding comes from the engine's own env (`ADA_FUNDING_SKEY_HEX`), not from
    /// a parameter — the client never handles the key.
    pub async fn prepare_lock(&self, swap_id: &str) -> Result<wire::LockUtxo, CryptoError> {
        // A generous budget rather than the 30s default: this builds and signs
        // against live protocol parameters over Blockfrost. Under-budgeting a
        // chain call is how C8 wedged a wallet-rpc for twenty minutes.
        let v = self
            .sidecar
            .call_with_timeout(
                "prepare_lock",
                serde_json::json!({ "swapId": swap_id }),
                WALLET_RESTORE_TIMEOUT,
            )
            .await
            .map_err(CryptoError::from)?;
        Ok(wire::LockUtxo {
            txid: req_str(&v, "txid", "prepare_lock")?,
            index: v.get("index").and_then(|i| i.as_i64()).ok_or_else(|| {
                CryptoError::Unavailable(
                    "prepare_lock returned no numeric `index`, so the prepared UTxO cannot be \
                     identified and M3 would bind the wrong input"
                        .into(),
                )
            })?,
            amount: v.get("amount").and_then(|a| a.as_i64()).ok_or_else(|| {
                CryptoError::Unavailable(
                    "prepare_lock returned no numeric `amount`, so the canonical refund body \
                     cannot be reconstructed"
                        .into(),
                )
            })?,
        })
    }

    /// **LEADER, phase 2 of 2.** Broadcast the lock prepared by [`Self::prepare_lock`].
    /// **This moves value.**
    ///
    /// Call it only once the counterparty's refund pre-signature has been
    /// received AND verified — before that, this puts funds into a script we
    /// cannot cooperatively exit.
    pub async fn submit_lock(&self, swap_id: &str) -> Result<String, CryptoError> {
        self.txid_call("submit_lock", swap_id).await
    }

    /// Publish the T1 refund. **This moves value** — it is the only method on
    /// this type that submits a transaction.
    ///
    /// The engine completes the refund from the pre-signature it stored at M3
    /// and broadcasts it, returning the txid. Publication is what reveals `s_a`
    /// on chain A, which is how the counterparty reclaims chain B (the desk's
    /// abort table, row 2) — so a refund that goes out is not a failure for
    /// either side, and one that silently does NOT go out is the worst outcome
    /// available. Hence: every error here is returned, never swallowed.
    pub async fn refund(&self, swap_id: &str) -> Result<String, CryptoError> {
        let v = self
            .sidecar
            .call("refund", serde_json::json!({ "swapId": swap_id }))
            .await
            .map_err(CryptoError::from)?;
        v.get("txid")
            .and_then(|t| t.as_str())
            .filter(|t| !t.is_empty())
            .map(str::to_string)
            .ok_or_else(|| {
                // A refund with no txid cannot be reported as broadcast: the
                // caller would mark the swap recovered and stop watching.
                CryptoError::Broadcast(format!(
                    "the engine accepted refund for swap {swap_id} but returned no txid, so \
                     there is nothing to confirm on chain - treating this as NOT broadcast"
                ))
            })
    }

    /// Recover the counterparty's revealed scalar from a claim or refund
    /// witness. Never returns the scalar itself — only whether the engine now
    /// holds it.
    ///
    /// The three-way `reason` is the point (A2). A `false` means one of three
    /// completely different things, and treating them alike either gives up on a
    /// recoverable coin or retries forever on one that is not:
    ///
    /// - `not-indexed` — the tx is not visible to the backend YET. Retry.
    /// - `unsupported-backend` — this backend can never do it. Permanent; a
    ///   human has to move.
    /// - `error:...` — transient. Retry.
    ///
    /// This is the same class distinction the transport preserves at the seam,
    /// applied to a chain read instead of an RPC.
    pub async fn extract_secret(
        &self,
        swap_id: &str,
        witness_txid: &str,
    ) -> Result<SecretExtraction, CryptoError> {
        let v = self
            .sidecar
            .call(
                "extract_secret",
                serde_json::json!({ "swapId": swap_id, "claimTxid": witness_txid }),
            )
            .await
            .map_err(CryptoError::from)?;
        Ok(SecretExtraction {
            secret_held: v
                .get("secretHeld")
                .and_then(serde_json::Value::as_bool)
                .unwrap_or(false),
            reason: v
                .get("reason")
                .and_then(|r| r.as_str())
                .unwrap_or_default()
                .to_string(),
        })
    }

    /// One poll of our OWN view of a lock. Raw report; the mapping onto the
    /// three states lives in [`super::observer`].
    ///
    /// C47a: WATCH lane — never queues on the pipe, yields to any pending
    /// protocol call. The observer already renders every transport error as
    /// COULD-NOT-LOOK, so a yielded round is a skipped poll, not a lie.
    pub async fn watch_lock(
        &self,
        swap_id: &str,
        chain: &str,
    ) -> Result<serde_json::Value, CryptoError> {
        self.sidecar
            .call_watch(
                "watch_lock",
                serde_json::json!({ "swapId": swap_id, "chain": chain }),
                WATCH_CALL_TIMEOUT,
            )
            .await
            .map_err(CryptoError::from)
    }

    /// Has the chain-A lock been SPENT, and by which transaction?
    ///
    /// This is what closes the refund-discovery gap (engine v11, shape 1): the
    /// follower finds the leader's refund itself instead of being told about it.
    /// A per-swap script address holds exactly one lock, so this is a two-tx
    /// history rather than a scan.
    ///
    /// Three states, never collapsed — same rule as `watch_lock`. A populated
    /// `error` means COULD NOT LOOK, which is emphatically not "not spent": read
    /// as the latter it would silence the very discovery this exists for.
    pub async fn watch_script_spend(&self, swap_id: &str) -> Result<SpendSighting, CryptoError> {
        // C47a: WATCH lane, same contract as `watch_lock` — the reclaim watch
        // treats every transport error as CouldNotLook-and-retry.
        let v = self
            .sidecar
            .call_watch(
                "watch_script_spend",
                serde_json::json!({ "swapId": swap_id }),
                WATCH_CALL_TIMEOUT,
            )
            .await
            .map_err(CryptoError::from)?;
        Ok(SpendSighting::from_engine(&v))
    }

    /// FOLLOWER reclaims chain B after the leader's refund leaked `s_a`.
    /// **Moves value.**
    /// `restore_height` is the Monero block to rebuild the joint wallet from.
    ///
    /// Optional, and the engine prefers it over anything in its own state (desk
    /// D18). It has to be passable because swaps recorded before the engine
    /// started storing `xmr_restore_height` have no usable height ANYWHERE — and
    /// the client cannot supply one by patching the state file, since `public` is
    /// covered by the D4 AAD. Without it the wallet restores from genesis: on
    /// stagenet that is ~2.17M blocks, which does not error, it just holds the
    /// single-threaded wallet-rpc for hours and starves every other caller.
    ///
    /// Too HIGH fails safe (the wallet never sees the output, the sweep finds
    /// nothing to spend); too low only costs scan time. So err high.
    pub async fn reclaim(
        &self,
        swap_id: &str,
        restore_height: Option<i64>,
    ) -> Result<String, CryptoError> {
        let mut params = serde_json::json!({ "swapId": swap_id });
        if let (Some(o), Some(h)) = (params.as_object_mut(), restore_height) {
            o.insert("restoreHeight".into(), serde_json::json!(h));
        }
        let v = self
            .sidecar
            .call_with_timeout("reclaim", params, WALLET_RESTORE_TIMEOUT)
            .await
            .map_err(CryptoError::from)?;
        v.get("txid")
            .and_then(|t| t.as_str())
            .filter(|t| !t.is_empty())
            .map(str::to_string)
            .ok_or_else(|| {
                CryptoError::Broadcast(format!(
                    "the engine accepted reclaim for swap {swap_id} but returned no txid, so \
                     there is nothing to confirm on chain - treating this as NOT reclaimed"
                ))
            })
    }

    // ── Rung-3 funded-choreography methods (consumed by the conductor) ──────
    //
    // Thin sidecar calls, added for the production driver. The safety ordering
    // that governs WHEN each may be called lives in `super::engine` (the gates)
    // and in the conductor; these are the downstream mechanism.

    /// Broadcast our lock: LEADER locks chain A (ADA), FOLLOWER locks chain B
    /// (XMR/ZEPH). **Moves value — the first irreversible on-chain step.**
    ///
    /// The caller MUST have passed the role-appropriate gate first. A FOLLOWER
    /// may call this ONLY after [`super::engine::safe_to_lock_follower`] confirms
    /// the LEADER's chain-A lock to depth — **observe A, then lock B**. Locking
    /// the scriptless coin before the scripted lock is confirmed is the
    /// directionality violation that strands funds; the gate is the precondition
    /// and this call is strictly downstream of it. (This is the exact inversion
    /// the desk caught in the driver design — encoded here so the method itself
    /// documents the ordering it depends on.)
    pub async fn lock(&self, swap_id: &str) -> Result<String, CryptoError> {
        self.txid_call("lock", swap_id).await
    }

    /// Complete and submit the cooperative CLAIM — the happy-path settlement,
    /// and **not** [`reclaim`](Self::reclaim). **Moves value.**
    ///
    /// `claim` completes the CLAIM adaptor pre-signature with the counterparty's
    /// revealed secret `t` to sweep the coin we are owed. `reclaim` completes the
    /// REFUND pre-signature with a leaked `s_a` after the counterparty aborts
    /// (abort-table row 2). Same crypto shape, opposite meaning — the desk caught
    /// this exact conflation in the design, so the happy path routes through
    /// `claim` and the abort path through `reclaim`, never the reverse.
    pub async fn claim(&self, swap_id: &str) -> Result<String, CryptoError> {
        self.txid_call("claim", swap_id).await
    }

    /// LEADER-only deep-abort escape after T2: sweep chain A alone when the
    /// counterparty is gone and even cooperative refund is unavailable (the
    /// `all[after T2, sigA]` branch). **Moves value.**
    pub async fn swipe(&self, swap_id: &str) -> Result<String, CryptoError> {
        self.txid_call("swipe", swap_id).await
    }

    /// Relay the counterparty's chain-B lock txid so a LEADER can run its own
    /// `watch_lock('B')` M5 gate against it — never trusting the desk's word for
    /// the lock it is about to gate on.
    pub async fn set_lock_b_txid(&self, swap_id: &str, txid: &str) -> Result<(), CryptoError> {
        self.sidecar
            .call(
                "set_lock_b_txid",
                serde_json::json!({ "swapId": swap_id, "txid": txid }),
            )
            .await
            .map(|_| ())
            .map_err(CryptoError::from)
    }

    /// FOLLOWER stores the LEADER's released claim adaptor pre-signature so
    /// [`claim`](Self::claim) can complete it with `t`. **The previously-missing
    /// caller of the M5 delivery.**
    ///
    /// The delivery mechanism mirrors by direction (the desk's answer to the
    /// design's open Q1): SELL_FOLLOWER polls `/status.releasedClaimSig` off the
    /// desk and feeds the released sig here; BUY_FOLLOWER is the LEADER and
    /// *releases* its own sig via `POST /ready-ack` instead, so it never ingests.
    /// This method is therefore the SELL side of the M5 wire.
    pub async fn ingest_claim_presig(
        &self,
        swap_id: &str,
        presig: &wire::AdaptorPresig,
    ) -> Result<(), CryptoError> {
        self.sidecar
            .call(
                "ingest_claim_presig",
                serde_json::json!({ "swapId": swap_id, "rEnc": presig.r_enc, "sp": presig.sp }),
            )
            .await
            .map(|_| ())
            .map_err(CryptoError::from)
    }

    /// Shared helper for the value-moving methods that return `{txid}`. A missing
    /// or empty txid is treated as NOT broadcast — reporting a submission that
    /// did not happen would mark the swap advanced and stop the watchers.
    async fn txid_call(&self, method: &'static str, swap_id: &str) -> Result<String, CryptoError> {
        // Value-moving calls get the wallet-restore budget: the leader's `claim`
        // sweeps chain B through the same restore+rescan path as `reclaim`, and a
        // generous ceiling costs a fast call nothing.
        let v = self
            .sidecar
            .call_with_timeout(
                method,
                serde_json::json!({ "swapId": swap_id }),
                WALLET_RESTORE_TIMEOUT,
            )
            .await
            .map_err(CryptoError::from)?;
        v.get("txid")
            .and_then(|t| t.as_str())
            .filter(|t| !t.is_empty())
            .map(str::to_string)
            .ok_or_else(|| {
                CryptoError::Broadcast(format!(
                    "the engine accepted {method} for swap {swap_id} but returned no txid, so \
                     there is nothing to confirm on chain - treating this as NOT submitted"
                ))
            })
    }

    /// M3. The FOLLOWER produces its refund pre-signature (`ours`); the LEADER
    /// verifies the follower's under output-pinning (`verified`).
    ///
    /// **Needs read-only chain access**, and this is the subtle part: the
    /// canonical refund body's fee comes from live protocol parameters, so both
    /// parties must estimate against the SAME current params or they build
    /// different bodies, the txids differ, and the pre-signature "disagrees"
    /// when nothing is actually wrong. That failure is fail-closed (it blocks,
    /// it does not strand) but it is the one to recognise on sight.
    pub async fn exchange_refund_sigs(
        &self,
        swap_id: &str,
        counterparty: Option<&wire::AdaptorPresig>,
        counterparty_leg_sigs: Option<&wire::LegSigs>,
    ) -> Result<RefundSigExchange, CryptoError> {
        let mut params = serde_json::json!({ "swapId": swap_id });
        if let (Some(o), Some(cp)) = (params.as_object_mut(), counterparty) {
            o.insert(
                "counterpartyPresig".into(),
                serde_json::json!({ "rEnc": cp.r_enc, "sp": cp.sp }),
            );
        }
        // CC-23: the LTC leg's counterparty half. The engine reads these as
        // `refundParentSig` / `refundSpendSig` (desk_helper.py:913-914). Absent
        // on ADA, where the whole concept does not exist.
        if let (Some(o), Some(ls)) = (params.as_object_mut(), counterparty_leg_sigs) {
            o.insert(
                "refundParentSig".into(),
                serde_json::json!(ls.refund_parent_sig),
            );
            o.insert(
                "refundSpendSig".into(),
                serde_json::json!(ls.refund_spend_sig),
            );
        }
        let r = self
            .sidecar
            .call("exchange_refund_sigs", params)
            .await
            .map_err(CryptoError::from)?;

        let ours = match r.get("ours") {
            Some(v) if !v.is_null() => Some(wire::AdaptorPresig {
                r_enc: req_str(v, "rEnc", "exchange_refund_sigs")?,
                sp: req_str(v, "sp", "exchange_refund_sigs")?,
            }),
            _ => None,
        };
        // CC-23: our own pair, when this leg has one. The engine returns it
        // under `legSigs` (desk_helper.py:963). Absent on ADA, and absent from
        // an engine that predates the field - which is "this leg has no leg
        // sigs", not "the leg sigs were empty".
        let ours_leg = r.get("legSigs").and_then(|v| {
            let p = v.get("refundParentSig")?.as_str()?.trim();
            let sp = v.get("refundSpendSig")?.as_str()?.trim();
            if p.is_empty() || sp.is_empty() {
                return None;
            }
            Some(wire::LegSigs {
                refund_parent_sig: p.to_string(),
                refund_spend_sig: sp.to_string(),
            })
        });
        Ok(RefundSigExchange {
            ours,
            ours_leg_sigs: ours_leg,
            verified: r.get("verified").and_then(|v| v.as_bool()).unwrap_or(false),
            // Engine 6e5194b returns the refund txid derived by the engine running
            // this call — which on the leader path is OURS. Empty from the follower
            // path and from any pre-6e5194b engine; absence means "not derived here",
            // never "agreed".
            our_refund_txid: r
                .get("refundTxid")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string(),
        })
    }

    /// M5, the setReady gate. The LEADER releases its claim adaptor pre-sig ONLY
    /// after the engine's own chain-B watch AND `chain_b_confirmed` both agree.
    ///
    /// The engine gate is fail-closed, but it is the INNER belt: our own
    /// `engine::safe_to_release_claim_sig` must already have said yes before we
    /// call this. Never pass `true` on the desk's word — that is the H1
    /// setReady-timing theft.
    pub async fn release_claim_sig(
        &self,
        swap_id: &str,
        chain_b_confirmed: bool,
    ) -> Result<wire::AdaptorPresig, CryptoError> {
        let r = self
            .sidecar
            .call(
                "release_claim_sig",
                serde_json::json!({ "swapId": swap_id, "chainBConfirmed": chain_b_confirmed }),
            )
            .await
            .map_err(CryptoError::from)?;
        Ok(wire::AdaptorPresig {
            r_enc: req_str(&r, "rEnc", "release_claim_sig")?,
            sp: req_str(&r, "sp", "release_claim_sig")?,
        })
    }

    /// A liveness round-trip: spawn the sidecar (if not already) and verify it
    /// answers `ping` with `pong:true`. Called at ARM TIME (the desk's endorsed
    /// ping-on-arm) so a config fault — a bad interpreter, a missing engine dir,
    /// the exit-78 startup fault — surfaces THEN, at startup, rather than on the
    /// first funds-moving call. Returns the engine's reported preset (`env`).
    pub async fn ping(&self) -> Result<String, CryptoError> {
        let v = self
            .sidecar
            .call("ping", serde_json::json!({}))
            .await
            .map_err(CryptoError::from)?;
        if v.get("pong").and_then(serde_json::Value::as_bool) != Some(true) {
            return Err(CryptoError::Unavailable(format!(
                "engine ping did not answer pong:true (got {v})"
            )));
        }
        Ok(v.get("env").and_then(|e| e.as_str()).unwrap_or_default().to_string())
    }

    /// Stop the child cleanly (drop stdin -> EOF -> exit 0, PID-kill only if it
    /// lingers).
    pub async fn shutdown(&self) {
        self.sidecar.shutdown().await;
    }
}

/// The M3 exchange result. A FOLLOWER gets `ours` populated and `verified: true`
/// trivially (it produced, it did not verify); a LEADER gets `ours: None` and a
/// meaningful `verified`.
#[derive(Debug, Clone, PartialEq)]
pub struct RefundSigExchange {
    pub ours: Option<wire::AdaptorPresig>,
    /// CC-23: our half of the LTC leg's signature pair, when this leg has one.
    ///
    /// `None` on ADA and from an engine predating the field. That is "this leg
    /// has no leg sigs", never "the leg sigs were empty" - the conductor turns
    /// the second into a refusal rather than sending a half-populated M3.
    pub ours_leg_sigs: Option<wire::LegSigs>,
    pub verified: bool,
    /// The refund txid **our own** engine derived for this body (engine 6e5194b),
    /// on the leader path only — empty from the follower path and from any older
    /// engine, where absence means "not derived here", never "agreed".
    ///
    /// Surfaced in the M3 failure because a bare `verified=false` cannot
    /// distinguish a wrong body from a wrong UTxO from a bad signature. The desk's
    /// counterpart is NOT on the wire — `wire::RefundSigsResponse` carries no
    /// txid — so this is half a diff: it gives the operator a concrete value to
    /// relay rather than a boolean to argue about.
    pub our_refund_txid: String,
}

/// The Stage-A refund broadcaster: refuses, loudly and specifically.
///
/// It exists so the refund PATH is real and exercised — the watcher fires, the
/// record is loaded, the pre-signature is pulled out, and a broadcaster is
/// called with a fully-assembled request. Only the final chain submission is
/// absent, and its absence is reported rather than silently skipped.
pub struct UnavailableRefundBroadcaster;

impl RefundBroadcaster for UnavailableRefundBroadcaster {
    fn broadcast_refund<'a>(&'a self, req: &'a RefundRequest<'a>) -> BroadcastFuture<'a> {
        Box::pin(async move {
            // Mock material is refused FIRST: it is the more dangerous case,
            // because a real broadcaster handed mock pre-signatures would
            // publish garbage.
            if !req.provenance.is_real() {
                return Err(CryptoError::MockMaterialRefused);
            }
            Err(CryptoError::Unavailable(format!(
                "no refund broadcaster is wired for pair {} chain {} (swap {}). The vendored \
                 engine library supplies the chain-leg transaction builders; until it is \
                 present the pre-signed refund stays on disk and must be published manually.",
                req.pair, req.chain, req.swap_id
            )))
        })
    }
}

/// The REAL broadcaster: publishes through our OWN engine sidecar's `refund`.
///
/// It does not assemble a transaction. The engine holds the pre-signature and
/// the chain-leg builders, so this addresses the swap by id and lets the engine
/// complete the refund it already has — the same reason the crypto is not
/// re-implemented here. The client-side guards in
/// [`super::refund::execute_refund`] still run first, and they read the CLIENT's
/// persisted record rather than the engine's, so the two have to agree before
/// anything is published.
pub struct SidecarRefundBroadcaster;

impl RefundBroadcaster for SidecarRefundBroadcaster {
    fn broadcast_refund<'a>(&'a self, req: &'a RefundRequest<'a>) -> BroadcastFuture<'a> {
        Box::pin(async move {
            // Same ordering as the unavailable path — mock material is refused
            // before anything touches a chain. This is the one broadcaster that
            // CAN move value, so it is where the check earns its keep.
            if !req.provenance.is_real() {
                return Err(CryptoError::MockMaterialRefused);
            }
            let ActiveCrypto::Vendored(v) = active_crypto() else {
                return Err(CryptoError::Unavailable(
                    "the sidecar refund broadcaster was selected but no vendored engine is \
                     installed - refusing to report a refund as broadcast when nothing could \
                     have published it"
                        .into(),
                ));
            };
            v.refund(req.swap_id).await
        })
    }
}

/// The active crypto provider.
///
/// THE SWAP-IN POINT: return the vendored-library provider here and the whole
/// desk tier picks it up. Everything upstream is already written against the
/// trait.
pub fn active_crypto() -> &'static ActiveCrypto {
    ACTIVE.get_or_init(|| ActiveCrypto::Mock(MockDeskCrypto))
}

static ACTIVE: std::sync::OnceLock<ActiveCrypto> = std::sync::OnceLock::new();

/// THE SWAP-IN POINT. Install the vendored engine once, at startup, when the
/// interpreter + engine dir are configured. Returns `Err` if a provider is
/// already installed — a swap must never change providers mid-flight, and a
/// silent second install would make `provenance` a lie for swaps already
/// accepted under the first one.
pub fn install_vendored(sidecar: super::sidecar::EngineSidecar) -> Result<(), CryptoError> {
    ACTIVE
        .set(ActiveCrypto::Vendored(VendoredDeskCrypto::new(sidecar)))
        .map_err(|_| {
            CryptoError::Unavailable(
                "a crypto provider is already installed; the engine cannot be swapped in after \
                 the first swap has used one"
                    .into(),
            )
        })
}

/// The active refund broadcaster. Same swap-in story as [`active_crypto`].
pub fn active_refund_broadcaster() -> &'static dyn RefundBroadcaster {
    // Follows whatever crypto provider is installed rather than being switched
    // separately. Two independent switches is how a build ends up verifying
    // against a real engine while broadcasting through a stub — or, worse, the
    // reverse.
    match active_crypto() {
        ActiveCrypto::Vendored(_) => &SidecarRefundBroadcaster,
        ActiveCrypto::Mock(_) => &UnavailableRefundBroadcaster,
    }
}

/// True when BOTH halves of the seam are real. The accept path logs on this so
/// a build running placeholders can never look like a build that is not.
pub fn crypto_is_production_ready() -> bool {
    active_crypto().provenance().is_real()
}

// NOTE: the old `secret_for_storage` helper is gone with the secret it moved.
// The sidecar owns the spend-scalar share in its own encrypted store, addressed
// by `SwapKeyMaterial::engine_ref`, so there is nothing for Rust to persist.

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal init context. Only `swap_id`/`role`/`pair` vary across these
    /// tests; the terms are fixed because the mock ignores them.
    fn ctx<'a>(swap_id: &'a str, role: ClientRole, pair: &'a str) -> SwapInitContext<'a> {
        SwapInitContext {
            leader_proof: false,
            swap_id,
            role,
            pair,
            amount_a: "100",
            amount_b: "1",
            t0: 1_000,
            t1: 2_000,
            t2: 3_000,
            t1_slot: None,
            payout_address: "",   // tests/harness: empty = derive, the pre-wiring behaviour
            refund_address: "",   // ditto — empty means derive, as both sides did before D25
            t2_slot: None,
        }
    }

    #[test]
    fn mock_keygen_is_deterministic_per_context_and_role() {
        let c = MockDeskCrypto;
        let a = c
            .generate_swap_keys(&ctx("q_1", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        let b = c
            .generate_swap_keys(&ctx("q_1", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        assert_eq!(a.client_key_share_point, b.client_key_share_point);
        // A different quote must not reuse key material.
        let other = c
            .generate_swap_keys(&ctx("q_2", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        assert_ne!(a.client_key_share_point, other.client_key_share_point);
        // ...nor a different pair.
        let other_pair = c
            .generate_swap_keys(&ctx("q_1", ClientRole::Follower, "ZEPH/ADA"))
            .unwrap();
        assert_ne!(a.client_key_share_point, other_pair.client_key_share_point);
    }

    #[test]
    fn every_public_field_is_32_byte_hex() {
        let m = MockDeskCrypto
            .generate_swap_keys(&ctx("q_1", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        for v in [
            &m.client_key_share_point,
            &m.client_chain_a_pubkey,
            m.adaptor_point.as_ref().unwrap(),
            m.view_key.as_ref().unwrap(),
        ] {
            assert_eq!(v.len(), 64, "points are 32-byte hex per CONTRACT.md");
            assert!(v.chars().all(|c| c.is_ascii_hexdigit()));
        }
    }

    #[test]
    fn the_adaptor_point_follows_the_role_flip() {
        let c = MockDeskCrypto;
        // Client FOLLOWS (SELL_FOLLOWER): it contributes T + the view key in M2.
        let f = c
            .generate_swap_keys(&ctx("q", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        assert!(f.adaptor_point.is_some());
        assert!(f.view_key.is_some());
        // Client LEADS (BUY_FOLLOWER): the desk supplied both in M1, so the
        // client must send null - a value here would be wrong on the wire.
        let l = c
            .generate_swap_keys(&ctx("q", ClientRole::Leader, "XMR/ADA"))
            .unwrap();
        assert!(l.adaptor_point.is_none());
        assert!(l.view_key.is_none());
        assert!(l.keys_request().adaptor_point.is_none());
    }

    #[test]
    fn the_timelock_slots_follow_the_leader_opposite_to_the_adaptor_point() {
        let c = MockDeskCrypto;
        // Client LEADS (BUY_FOLLOWER): it commits its own chain-A refund window,
        // because only the scripted-coin holder can hold an on-chain refund.
        let l = c
            .generate_swap_keys(&ctx("q", ClientRole::Leader, "XMR/ADA"))
            .unwrap();
        assert_eq!(l.t1_slot, Some(MOCK_T1_SLOT));
        assert_eq!(l.t2_slot, Some(MOCK_T2_SLOT));
        assert!(l.t2_slot > l.t1_slot, "the desk sanity-checks t2 > t1 > 0");
        // ...and they reach M2, which is the whole point - the desk-as-follower
        // needs them to derive the chain-A address it watches our lock at.
        let req = l.keys_request();
        assert_eq!(req.t1_slot, Some(MOCK_T1_SLOT));
        assert_eq!(req.t2_slot, Some(MOCK_T2_SLOT));

        // Client FOLLOWS (SELL_FOLLOWER): the DESK committed the slots in M1, so
        // re-committing them here would let the follower set the leader's own
        // refund window. Must stay null.
        let f = c
            .generate_swap_keys(&ctx("q", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        assert_eq!(f.t1_slot, None);
        assert_eq!(f.t2_slot, None);
        assert!(f.keys_request().t1_slot.is_none());

        // The two role-flipped groups are exact opposites in the same message.
        assert!(l.adaptor_point.is_none() && l.t1_slot.is_some());
        assert!(f.adaptor_point.is_some() && f.t1_slot.is_none());
    }

    #[test]
    fn the_secret_never_equals_anything_that_crosses_the_wire() {
        let m = MockDeskCrypto
            .generate_swap_keys(&ctx("q", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        let req = m.keys_request();
        let wire_values = [
            Some(req.client_key_share_point.clone()),
            Some(req.client_chain_a_pubkey.clone()),
            req.adaptor_point.clone(),
            req.view_key.clone(),
            req.dleq_proof.clone(),
        ];
        // The old version of this test compared every wire field against the
        // in-Rust spend scalar. That scalar no longer exists here at all — the
        // sidecar owns it — so the property is now stronger and simpler: the only
        // thing Rust holds is a HANDLE, and the handle must not be on the wire
        // either (it is our local addressing, meaningless and misleading to the
        // desk).
        for v in wire_values.into_iter().flatten() {
            assert_ne!(
                v, m.engine_ref,
                "the sidecar handle is local addressing and must never be sent"
            );
        }
    }

        /// CLIENT-1 producing side: when the ENGINE hands us a proof, M2 carries it.
    ///
    /// The value is never synthesized here - it comes from the engine, which
    /// emits it only when the leg needs one and the swap negotiated the
    /// capability. This test therefore drives the material directly, which is
    /// exactly the seam a leg-aware engine will populate.
    #[test]
    fn m2_carries_the_dleq_proof_when_the_engine_supplies_one_client1() {
        let m = SwapKeyMaterial {
            client_key_share_point: "ks".into(),
            client_chain_a_pubkey: "ca".into(),
            // On the LTC leg the point is READ OUT of the proof; both travel or
            // neither does.
            adaptor_point: Some("029853c6".into()),
            view_key: None,
            dleq_proof: Some("deadbeef".into()),
            engine_ref: "eng".into(),
            t1_slot: Some(1),
            t2_slot: Some(2),
            provenance: KeyProvenance::Vendored,
        };
        let req = m.keys_request();
        assert_eq!(req.dleq_proof.as_deref(), Some("deadbeef"));
        assert_eq!(req.adaptor_point.as_deref(), Some("029853c6"));
        let j = serde_json::to_string(&req).unwrap();
        assert!(j.contains("\"dleqProof\":\"deadbeef\""), "{j}");
    }

    /// And the ADA guard that must NOT move: no engine-supplied proof means the
    /// field serializes as null, exactly as it always has.
    ///
    /// This is the C49 shape guarded in advance - widening the producing side
    /// for LTC must not widen it for ADA, and the wire must stay
    /// byte-identical for the leg that has settled swaps.
    #[test]
    fn m2_still_sends_null_when_the_engine_supplies_no_proof_client1() {
        let m = SwapKeyMaterial {
            client_key_share_point: "ks".into(),
            client_chain_a_pubkey: "ca".into(),
            adaptor_point: Some("ap".into()),
            view_key: Some("vk".into()),
            dleq_proof: None,
            engine_ref: "eng".into(),
            t1_slot: None,
            t2_slot: None,
            provenance: KeyProvenance::Vendored,
        };
        let j = serde_json::to_string(&m.keys_request()).unwrap();
        // present-with-null, NOT omitted: a vanished key makes the desk misread
        // the role, which is the #1 porting mistake this mirror exists to stop.
        assert!(j.contains("\"dleqProof\":null"), "must stay present-with-null: {j}");
    }

    #[test]
    fn keys_request_never_carries_a_dleq_proof_on_the_ada_leg() {
        // Same curve both legs - a proof here would be meaningless and would
        // signal cross-curve to the desk.
        let m = MockDeskCrypto
            .generate_swap_keys(&ctx("q", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        assert!(m.keys_request().dleq_proof.is_none());
    }

    #[test]
    fn presig_round_trips_its_own_verifier() {
        let c = MockDeskCrypto;
        let m = c
            .generate_swap_keys(&ctx("q", ClientRole::Follower, "XMR/ADA"))
            .unwrap();
        let ctx = RefundSignContext {
            swap_id: "s1",
            pair: "XMR/ADA",
            direction: "SELL_FOLLOWER",
            refund_address: "addr_refund",
            t1_unix: 2_000,
        };
        let p = c.presign_refund(&m, &ctx).unwrap();
        assert_eq!(c.verify_presig(&p, &ctx), Ok(()));
    }

    #[test]
    fn verify_rejects_a_malformed_presig() {
        let ctx = RefundSignContext {
            swap_id: "s1",
            pair: "XMR/ADA",
            direction: "SELL_FOLLOWER",
            refund_address: "a",
            t1_unix: 1,
        };
        let bad = wire::AdaptorPresig {
            r_enc: "nope".into(),
            sp: "also-nope".into(),
        };
        assert!(MockDeskCrypto.verify_presig(&bad, &ctx).is_err());
    }

    #[test]
    fn provenance_round_trips_and_defaults_to_the_safe_value() {
        assert_eq!(KeyProvenance::parse("vendored"), KeyProvenance::Vendored);
        assert_eq!(KeyProvenance::parse("mock"), KeyProvenance::Mock);
        // An unrecognized or absent value must degrade to Mock, which is
        // REFUSED downstream - never to Vendored, which is acted on.
        assert_eq!(KeyProvenance::parse(""), KeyProvenance::Mock);
        assert_eq!(KeyProvenance::parse("garbage"), KeyProvenance::Mock);
        assert!(!KeyProvenance::Mock.is_real());
        assert!(KeyProvenance::Vendored.is_real());
    }

    #[tokio::test]
    async fn the_broadcaster_refuses_mock_material_before_anything_else() {
        let presig = wire::AdaptorPresig {
            r_enc: "aa".repeat(32),
            sp: "bb".repeat(32),
        };
        let req = RefundRequest {
            swap_id: "s1",
            pair: "XMR/ADA",
            direction: "SELL_FOLLOWER",
            refund_address: "addr",
            refund_presig: presig.clone(),
            chain: "B",
            lock_txid: "tx",
            provenance: KeyProvenance::Mock,
        };
        assert_eq!(
            UnavailableRefundBroadcaster.broadcast_refund(&req).await,
            Err(CryptoError::MockMaterialRefused)
        );

        // With real provenance it still cannot broadcast - but the error now
        // names the missing piece instead of the material.
        let real = RefundRequest {
            provenance: KeyProvenance::Vendored,
            refund_presig: presig,
            ..req
        };
        match UnavailableRefundBroadcaster.broadcast_refund(&real).await {
            Err(CryptoError::Unavailable(msg)) => {
                assert!(msg.contains("XMR/ADA"), "the error should name the pair");
                assert!(msg.contains("s1"), "and the swap");
            }
            other => panic!("expected Unavailable, got {other:?}"),
        }
    }

    // ── LIVE: the vendored provider against the real v8 engine ────────────
    //
    // These drive TWO real sidecars through `VendoredDeskCrypto` — one playing
    // us, one playing the desk — and assert they independently derive the SAME
    // chain-A lock address and chain-B joint address. That agreement IS the
    // offline half of the handshake, and it is what proves our Rust marshalling
    // matches the desk's. Skips when the engine env is unset so `cargo test`
    // stays green without Python.

    fn live_provider(tag: &str) -> Option<VendoredDeskCrypto> {
        let python = std::env::var("PWNDA_ENGINE_TEST_PYTHON").ok()?;
        let dir = std::env::var("PWNDA_ENGINE_TEST_DIR").ok()?;
        // Separate data dirs so the two sides cannot share engine state - they
        // must agree by cryptography, not by accident.
        let data = std::env::temp_dir().join(format!("pwnda-seam-{tag}"));
        let _ = std::fs::remove_dir_all(&data);
        let cfg = super::super::sidecar::SidecarConfig::new(python, dir, "dev")
            .unwrap()
            .with_data_dir(data.display().to_string())
            .with_env("ADA_ENGINE_STATE_KEY", "11".repeat(32))
            .unwrap()
            // Required since engine v12 (D5). Names no real resource on purpose
            // - see `sidecar::OFFLINE_TEST_WALLET_RPC`. This is the `dev`
            // preset, whose address prefix matches MAINNET, so a plausible-
            // looking wallet URL here is the most dangerous kind.
            .with_env("XMR_WALLET_RPC", "http://127.0.0.1:1/json_rpc")
            .unwrap();
        Some(VendoredDeskCrypto::new(
            super::super::sidecar::EngineSidecar::new(cfg),
        ))
    }

    /// Absolute slots the LEADER commits. Supplied explicitly so `init_swap`
    /// stays OFFLINE — an unsupplied leader would derive from the live chain
    /// tip, which is rung-2b territory.
    const T1: i64 = 84_600_000;
    const T2: i64 = 84_603_600;

    fn init_ctx<'a>(
        swap_id: &'a str,
        role: ClientRole,
        t1_slot: Option<i64>,
        t2_slot: Option<i64>,
    ) -> SwapInitContext<'a> {
        SwapInitContext {
            leader_proof: false,
            swap_id,
            role,
            pair: "XMR/ADA",
            amount_a: "100",
            amount_b: "1",
            t0: 1_000,
            t1: 2_000,
            t2: 3_000,
            t1_slot,
            t2_slot,
            payout_address: "",   // harness: empty = derive (pre-wiring behaviour)
            refund_address: "",   // harness: empty = derive, as before D25
        }
    }

    #[tokio::test]
    async fn live_sell_follower_offline_half_agrees() {
        let (Some(us), Some(desk)) = (live_provider("sell-us"), live_provider("sell-desk")) else {
            eprintln!("skipping: set PWNDA_ENGINE_TEST_PYTHON + PWNDA_ENGINE_TEST_DIR");
            return;
        };
        let id = "seam_sell_1";

        // The DESK leads and commits the slots (its M1).
        let desk_m1 = desk
            .generate_swap_keys(&init_ctx(id, ClientRole::Leader, Some(T1), Some(T2)))
            .await
            .expect("desk init_swap(LEADER)");
        assert_eq!(desk_m1.t1_slot, Some(T1), "the leader commits the slots");

        // WE follow: we contribute the adaptor point + view key, no slots.
        let ours = us
            .generate_swap_keys(&init_ctx(id, ClientRole::Follower, Some(T1), Some(T2)))
            .await
            .expect("our init_swap(FOLLOWER)");
        assert!(ours.adaptor_point.is_some() && ours.view_key.is_some());
        assert_eq!(ours.t1_slot, None, "a follower must not commit slots");
        // The same-curve invariant the desk enforces on our M2.
        assert_eq!(ours.adaptor_point, Some(ours.client_key_share_point.clone()));
        // And the M2 we would actually send carries null slots.
        assert_eq!(ours.keys_request().t1_slot, None);

        // Each side ingests the other's half. We pass the desk's slots (it leads).
        let our_joint = us
            .ingest_counterparty(id, &cp_from(&desk_m1, Some(T1), Some(T2)))
            .await
            .expect("we ingest the desk M1");
        let desk_joint = desk
            .ingest_counterparty(id, &cp_from(&ours, None, None))
            .await
            .expect("desk ingests our M2");

        assert_eq!(
            our_joint, desk_joint,
            "both sides must derive the SAME joint key + lock addresses"
        );
        assert!(our_joint.chain_a_lock_addr.starts_with("addr"));
        us.shutdown().await;
        desk.shutdown().await;
    }

    #[tokio::test]
    async fn live_buy_follower_offline_half_agrees() {
        let (Some(us), Some(desk)) = (live_provider("buy-us"), live_provider("buy-desk")) else {
            eprintln!("skipping: engine test env not set");
            return;
        };
        let id = "seam_buy_1";

        // WE lead: we commit the chain-A refund window.
        let ours = us
            .generate_swap_keys(&init_ctx(id, ClientRole::Leader, Some(T1), Some(T2)))
            .await
            .expect("our init_swap(LEADER)");
        assert_eq!(ours.t1_slot, Some(T1));
        assert!(ours.adaptor_point.is_none(), "a leader sends no adaptor point");
        // The M2 we send carries the slots - this is the v7 co-implement.
        assert_eq!(ours.keys_request().t1_slot, Some(T1));

        // The DESK follows, and inits with slots UNRESOLVED - the path v8 fixed.
        let desk_m1 = desk
            .generate_swap_keys(&init_ctx(id, ClientRole::Follower, None, None))
            .await
            .expect("desk init_swap(FOLLOWER) with deferred slots - broken before v8");
        assert!(desk_m1.adaptor_point.is_some(), "the follower contributes T");

        // We ingest the desk's half (no slots - it follows); the desk ingests
        // ours WITH our committed slots, which is how it reaches our address.
        let our_joint = us
            .ingest_counterparty(id, &cp_from(&desk_m1, None, None))
            .await
            .expect("we ingest the desk material");
        let desk_joint = desk
            .ingest_counterparty(id, &cp_from(&ours, Some(T1), Some(T2)))
            .await
            .expect("desk ingests our M2 slots");

        assert_eq!(
            our_joint, desk_joint,
            "the desk must reach OUR chain-A address from the slots we committed"
        );
        us.shutdown().await;
        desk.shutdown().await;
    }

    /// Build the counterparty view of a party's own material.
    fn cp_from<'a>(
        m: &'a SwapKeyMaterial,
        t1_slot: Option<i64>,
        t2_slot: Option<i64>,
    ) -> CounterpartyKeys<'a> {
        CounterpartyKeys {
            key_share_point: &m.client_key_share_point,
            chain_a_pubkey: &m.client_chain_a_pubkey,
            adaptor_point: m.adaptor_point.as_deref(),
            view_key: m.view_key.as_deref(),
            dleq_proof: None,
            t1_slot,
            t2_slot,
            claim_dest: None,
            refund_dest: None,
        }
    }

    #[test]
    fn the_transports_error_class_survives_the_seam() {
        use super::super::sidecar::SidecarError as S;

        // An engine refusal must stay a refusal. Flattening it to Unavailable
        // (which is what this code did until rung 2b's plumbing check exposed
        // it) invites a retry, and retrying a theft-class rejection is the loop
        // that must not exist.
        let rejected: CryptoError = S::EngineRejected {
            method: "ingest_counterparty".into(),
            error_type: "EngineError".into(),
            message: "require_subgroup: not a prime-order point".into(),
        }
        .into();
        assert!(rejected.is_engine_rejection());
        assert!(rejected.is_permanent(), "never retry an engine refusal");

        // A config fault is permanent too, but a DIFFERENT permanence: fix the
        // config rather than the call.
        let cfg: CryptoError = S::ConfigFault("no ADA_ENGINE_ENV".into()).into();
        assert!(cfg.is_permanent());
        assert!(!cfg.is_engine_rejection());

        // A death is NOT permanent - restart-and-rehydrate is the right move.
        let died: CryptoError = S::SidecarDied {
            last_method: "init_swap".into(),
            code: Some(1),
        }
        .into();
        assert!(!died.is_permanent(), "a dead sidecar is worth respawning");
        assert!(!died.is_engine_rejection());
    }

    #[test]
    fn stage_a_is_not_production_ready_and_says_so() {
        assert!(
            !crypto_is_production_ready(),
            "the placeholder provider must never report itself production-ready"
        );
        assert_eq!(active_crypto().provenance(), KeyProvenance::Mock);
    }
}
