//! OS-backed secure entropy for wallet seed generation.
//!
//! Sources entropy from the operating-system CSPRNG via the `getrandom` crate
//! (Windows: `BCryptGenRandom`; Linux: `getrandom(2)` syscall; macOS:
//! `SecRandomCopyBytes`). This is the same source WebCrypto's
//! `crypto.getRandomValues` ultimately consults inside WebView2 — but routing
//! through Rust means seed bytes never touch the JS engine during creation,
//! avoiding the entire class of "WebView sandboxing surprised us" risks and
//! making the trust boundary trivially auditable.
//!
//! Used by:
//!   - BIP39 mnemonic generation (16 bytes / 128 bits)
//!   - Monero legacy 25-word seeds (32 bytes / 256 bits, reduced mod-l)
//!   - Polyseed 16-word seeds (19 bytes / 152 bits, top 2 bits cleared = 150)
//!   - Zephyr 25-word seeds (32 bytes / 256 bits, same as XMR)
//!
//! Not used for:
//!   - Vault salt/IV — generated by WebCrypto `getRandomValues` in
//!     `src/crypto.ts`. AES-GCM nonces don't require the same trust path
//!     since they're not the long-lived secret.

/// Maximum entropy buffer the renderer is allowed to request. 64 bytes covers
/// every wallet seed format we ship (the largest is 32 bytes for Monero/Zephyr
/// 256-bit seeds) with headroom for future schemes. Larger requests are
/// almost certainly a bug or a misuse.
const MAX_BYTES: usize = 64;

/// Fill a buffer of `byte_count` bytes with cryptographically secure
/// OS entropy. Used by the frontend `secureRandomBytes()` helper to seed
/// every wallet mnemonic at creation time.
///
/// Returns the bytes as `Vec<u8>` — Tauri serializes this to a JS
/// `number[]` over IPC; the renderer wraps it back in `Uint8Array`.
///
/// Errors:
///   - `byte_count` is 0 or > 64 (sanity bound; see `MAX_BYTES`).
///   - The OS entropy syscall fails (extraordinarily rare; surfaces the
///     `getrandom::Error` Display string).
#[tauri::command]
pub fn generate_seed_entropy(byte_count: usize) -> Result<Vec<u8>, String> {
    if byte_count == 0 {
        return Err("byte_count must be > 0".into());
    }
    if byte_count > MAX_BYTES {
        return Err(format!(
            "byte_count {} exceeds maximum {} — refusing to allocate",
            byte_count, MAX_BYTES
        ));
    }

    let mut buf = vec![0u8; byte_count];
    getrandom::getrandom(&mut buf).map_err(|e| {
        format!(
            "OS entropy syscall failed: {}. This should never happen on a healthy system.",
            e
        )
    })?;
    Ok(buf)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_zero_bytes() {
        assert!(generate_seed_entropy(0).is_err());
    }

    #[test]
    fn rejects_oversized_request() {
        assert!(generate_seed_entropy(65).is_err());
        assert!(generate_seed_entropy(usize::MAX).is_err());
    }

    #[test]
    fn returns_requested_size() {
        for n in [1, 16, 19, 32, 64] {
            let bytes = generate_seed_entropy(n).expect("OS entropy unavailable");
            assert_eq!(bytes.len(), n, "wrong length for n={}", n);
        }
    }

    #[test]
    fn two_calls_differ() {
        // Probability of collision in 32 bytes is 2^-256. Any failure here
        // means the OS RNG is broken (or this test is being run under a
        // record-and-replay debugger that's faking syscalls).
        let a = generate_seed_entropy(32).unwrap();
        let b = generate_seed_entropy(32).unwrap();
        assert_ne!(a, b, "two consecutive 32-byte draws were identical");
    }

    #[test]
    fn output_is_not_all_zeros() {
        // Same statistical argument — a 32-byte all-zero output from a
        // CSPRNG is 2^-256 likely. If this fires, something is wrong with
        // getrandom or the buffer wasn't actually filled.
        let bytes = generate_seed_entropy(32).unwrap();
        assert!(bytes.iter().any(|&b| b != 0));
    }
}
