/**
 * The three NEAR-Intents registries must agree.
 *
 * There are three separate places that answer "can this asset go through
 * NEAR Intents", and on 2026-08-25 all three disagreed at once:
 *
 *  1. `near-intents-assets.generated.ts` — the upstream 1Click catalog,
 *     regenerated by `npm run sync-intents-assets`. Authoritative on *which
 *     assets exist*.
 *  2. `PWNDA_INTENTS_SOURCE_TICKERS` / `..._DESTINATION_TICKERS` — hand-kept
 *     arrays that decide what the coin picker OFFERS.
 *  3. `ASSET_CAPABILITIES[X].nearIntentsAsset` — the field
 *     `isIntentsRoutableFromRegistry` actually gates a quote on.
 *
 * The observed symptoms, both reported by the operator:
 *
 *  - **LTC was offered but not routable.** It sat in the catalog (1) and the
 *    picker roster (2) while (3) was still `null` from a May 2026 note saying
 *    it was not in the OMFT list. Upstream added it; nothing updated (3). It
 *    was the ONLY asset in the registry that disagreed with the catalog.
 *  - **XMR was offered on the NEAR tab and cannot be.** Monero is not on
 *    1Click at all — not one entry in the upstream feed — but the picker
 *    unioned the desk assets onto every non-BasicSwap route.
 *
 * `npm run check-intents-assets` compares (1) against upstream and is the
 * reason the catalog was right. **It has never compared (2) or (3)**, which
 * is why the drift lived there. These tests close that gap in the direction
 * the checker cannot see.
 */
import { describe, it, expect } from "vitest";
import { ASSET_CAPABILITIES } from "./asset-capabilities";
import { NEAR_INTENTS_ASSETS } from "./near-intents-assets.generated";
import { SOURCE_CAPABLE_BLOCKCHAINS } from "./intents-source-capability";
import { getDropdownTickers, isIntentsRoutable } from "./swap-data";

/** Every symbol the shipped upstream catalog carries, uppercased. */
const CATALOG_SYMBOLS = new Set(
  NEAR_INTENTS_ASSETS.map((a) => a.symbol.toUpperCase()),
);

describe("intents capability matches the shipped catalog", () => {
  it("no asset claims an Intents route the catalog does not carry", () => {
    // This direction is the dangerous one: a route the wallet offers and
    // 1Click cannot serve fails at quote time, after the user has committed
    // attention to the pair.
    const claimsButAbsent = Object.entries(ASSET_CAPABILITIES)
      .filter(([t, c]) => c.nearIntentsAsset && !CATALOG_SYMBOLS.has(t.toUpperCase()))
      .map(([t]) => t);
    expect(
      claimsButAbsent,
      "these assets carry a nearIntentsAsset but are absent from the shipped " +
        "catalog — either the catalog is stale (run sync-intents-assets) or " +
        "the capability is wrong",
    ).toEqual([]);
  });

  it("no catalogued asset the wallet holds is silently left unroutable", () => {
    // The LTC failure, pinned. An asset present in the catalog AND known to
    // the wallet, with `nearIntentsAsset: null`, is a route quietly switched
    // off — which is exactly how LTC sat dark for three months.
    const catalogedButNull = Object.entries(ASSET_CAPABILITIES)
      .filter(([t, c]) => !c.nearIntentsAsset && CATALOG_SYMBOLS.has(t.toUpperCase()))
      .map(([t]) => t);
    expect(
      catalogedButNull,
      "upstream routes these and the wallet holds them, but nearIntentsAsset " +
        "is null — if that is deliberate, say why in a comment on the field " +
        "and add the ticker to this test's allow-list",
    ).toEqual([]);
  });

  it("LTC specifically is routable — the 2026-08-25 regression", () => {
    expect(ASSET_CAPABILITIES.LTC.nearIntentsAsset).toBe("nep141:ltc.omft.near");
    expect(SOURCE_CAPABLE_BLOCKCHAINS.has("ltc")).toBe(true);
    expect(isIntentsRoutable("LTC", "BTC")).toBe(true);
  });

  it("XMR and ZEPH stay unroutable — they are genuinely not on 1Click", () => {
    // The negative control. If this ever goes green because someone set a
    // nearIntentsAsset on a Monero-family asset, the first test above would
    // also fire — but naming it here makes the intent unmissable.
    expect(CATALOG_SYMBOLS.has("XMR")).toBe(false);
    expect(CATALOG_SYMBOLS.has("ZEPH")).toBe(false);
    expect(ASSET_CAPABILITIES.XMR.nearIntentsAsset).toBeNull();
    expect(isIntentsRoutable("XMR", "BTC")).toBe(false);
  });
});

describe("the NEAR tab's picker offers only what NEAR can carry", () => {
  it("does not offer desk-only assets on the intents route", () => {
    const near = getDropdownTickers({ router: "intents" });
    expect(near, "XMR is not on 1Click — offering it can only end in 'no route'")
      .not.toContain("XMR");
    expect(near).not.toContain("ZEPH");
  });

  it("still offers them on Auto, where another router may serve the pair", () => {
    // The union is CORRECT for Auto — that is the tab where BasicSwap might
    // pick the pair up. Narrowing it there would hide a working route.
    const auto = getDropdownTickers({});
    expect(auto).toContain("XMR");
  });

  it("offers LTC on the intents route", () => {
    expect(getDropdownTickers({ router: "intents", sourceOnly: true })).toContain("LTC");
  });

  it("every ticker the intents picker offers is actually routable", () => {
    // The invariant that makes picker and gate agree by construction: if this
    // holds, no selection on the NEAR tab can produce "no route" for a
    // registry reason. (A pair can still lack liquidity — that is upstream's
    // answer to give, not ours to pre-empt.)
    const offered = getDropdownTickers({ router: "intents" });
    const notRoutable = offered.filter(
      (t) => !ASSET_CAPABILITIES[t.toUpperCase()]?.nearIntentsAsset,
    );
    expect(notRoutable).toEqual([]);
  });
});
